-- ============================================================================
-- V1__init_ltt.sql — Khoi tao bang LTT va cac bang phu tro
-- Module: TT.OUT.MANUAL — Lenh thanh toan di NHNN thu cong
-- Oracle 19c DDL
-- Generated: 2026-05-10 | SA + DBA — Stage 2
-- Reference: states.yaml (15 states), screens.yaml (S02, 57 fields),
--            coa-segments.yaml (11 COA segments), permissions.yaml (4 roles)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Sequence cho khoa chinh LTT
-- ---------------------------------------------------------------------------
CREATE SEQUENCE SEQ_LTT_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ---------------------------------------------------------------------------
-- Bang LTT — Lenh thanh toan (ban ghi chinh)
-- 57 truong nghiep vu tu screens.yaml S02 + truong ky thuat
-- ---------------------------------------------------------------------------
CREATE TABLE LTT (
    -- === Khoa chinh & dinh danh ===
    ID                          NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- So yeu cau thanh toan / So but toan
    SO_YCTT                     VARCHAR2(30)    NOT NULL,
    -- Ma dinh danh duy nhat (idempotency) cho moi REST POST / MQ message
    IDEMPOTENCY_KEY             VARCHAR2(64)    UNIQUE,

    -- === Trang thai (states.yaml — 15 trang thai) ===
    STATE                       VARCHAR2(25)    NOT NULL,
    -- Trang thai truoc khi bi BLOCK (de UNBLOCK quay lai)
    PREV_STATE                  VARCHAR2(25),

    -- === Nhom 1: Thong tin chung (screens.yaml S02 — group "Thong tin chung") ===
    -- Kenh thanh toan (DM-CHANNEL: LNH, SP, LKB)
    CHANNEL                     VARCHAR2(5)     NOT NULL,
    -- Loai lenh thanh toan (DM-ORDER-TYPE: OT-LNH-LCC, OT-SP-CK, ...)
    ORDER_TYPE                  VARCHAR2(12)    NOT NULL,
    -- NH/KB chuyen (DM-BANK: ma 8 ky tu BIN)
    SENDER_BANK_CODE            VARCHAR2(8)     NOT NULL,
    -- NH/KB nhan (DM-BANK: ma 8 ky tu BIN)
    RECEIVER_BANK_CODE          VARCHAR2(8)     NOT NULL,
    -- Ngay thanh toan
    PAYMENT_DATE                DATE            NOT NULL,
    -- So tien chuyen (VND hoac quy doi ra VND)
    AMOUNT                      NUMBER(18,2)    NOT NULL,
    -- Loai tien (DM-CURRENCY: VND, USD, EUR, ...)
    CURRENCY                    VARCHAR2(3)     DEFAULT 'VND' NOT NULL,
    -- Loai giao dich chi kenh LNH (DM-TXN-TYPE: TX-LCC, TX-LCT, ...)
    TXN_TYPE                    VARCHAR2(6),
    -- Ty gia (chi ngoai te)
    EXCHANGE_RATE               NUMBER(12,5),
    -- So chung tu goc (bat buoc khi kenh SP)
    ORIG_DOC_NO                 VARCHAR2(30),
    -- Ngay chung tu
    ORIG_DOC_DATE               DATE,
    -- Loai phi (DM-FEE-TYPE: FE-OUR, FE-BEN, ...)
    FEE_TYPE                    VARCHAR2(8),
    -- Ma ngoai te trich no (DM-CURRENCY)
    DEBIT_CCY                   VARCHAR2(3),
    -- Ma ngoai te thanh toan (DM-CURRENCY)
    PAYMENT_CCY                 VARCHAR2(3),
    -- So tien ngoai te thanh toan
    PAYMENT_CCY_AMOUNT          NUMBER(18,2),
    -- Noi dung thanh toan
    PAYMENT_CONTENT             VARCHAR2(500)   NOT NULL,
    -- Ma TPCP — Trai phieu chinh phu (bat buoc khi loai lenh = OT-SP-TPCP)
    TPCP_CODE                   VARCHAR2(20),

    -- === Nhom 2: COA Segments (screens.yaml S02 — group "Thong tin khoan muc") ===
    -- Moi LTT co 1 to hop COA chinh; chi tiet nhieu dong nam bang LTT_LINE_ITEM
    -- Ma quy (DM-MAQUY: 2 ky tu)
    COA_FUND                    VARCHAR2(2)     DEFAULT '01',
    -- Tai khoan tu nhien (DM-TK: 4 ky tu)
    COA_NATURAL_ACCOUNT         VARCHAR2(4),
    -- Don vi quan he ngan sach (DM-DVQHNS: 7 ky tu)
    COA_DVQHNS                  VARCHAR2(7),
    -- Cap ngan sach (DM-CAPNS: 1 ky tu)
    COA_BUDGET_LEVEL            VARCHAR2(1),
    -- Chuong (DM-CHUONG: 3 ky tu)
    COA_CHAPTER                 VARCHAR2(3)     DEFAULT '000',
    -- Nganh kinh te (DM-NGANHKT: 3 ky tu)
    COA_INDUSTRY                VARCHAR2(3)     DEFAULT '000',
    -- Noi dung kinh te (DM-NDKT: 4 ky tu)
    COA_NDKT                    VARCHAR2(4)     DEFAULT '0000',
    -- Dia ban (DM-DIABAN: 5 ky tu)
    COA_AREA                    VARCHAR2(5)     DEFAULT '00000',
    -- Chuong trinh muc tieu (DM-CTMT: 5 ky tu)
    COA_PROGRAM                 VARCHAR2(5)     DEFAULT '00000',
    -- Ma nguon kinh phi (DM-MN: 2 ky tu)
    COA_FUND_SOURCE             VARCHAR2(2)     DEFAULT '00',
    -- Kho bac (DM-KB: 4 ky tu)
    COA_TREASURY                VARCHAR2(4)     DEFAULT '0000',
    -- Ma du phong (DM-DP: 3 ky tu)
    COA_RESERVE                 VARCHAR2(3)     DEFAULT '000',

    -- === Nhom 3: Thong tin nguoi chuyen (screens.yaml S02 — group "Thong tin nguoi chuyen") ===
    SENDER_NAME                 VARCHAR2(200)   NOT NULL,
    SENDER_ADDRESS              VARCHAR2(250),
    SENDER_ACCOUNT              VARCHAR2(25),
    SENDER_CUSTOMER_CODE        VARCHAR2(20),
    -- Mo tai NH/KB (DM-BANK)
    SENDER_BANK_NAME            VARCHAR2(200),
    SENDER_ID_NUMBER            VARCHAR2(20),
    SENDER_ID_ISSUE_DATE        DATE,
    SENDER_ID_ISSUE_PLACE       VARCHAR2(100),

    -- === Nhom 4: Thong tin nguoi nhan (screens.yaml S02 — group "Thong tin nguoi nhan") ===
    RECEIVER_NAME               VARCHAR2(200)   NOT NULL,
    RECEIVER_ADDRESS            VARCHAR2(250),
    RECEIVER_ACCOUNT            VARCHAR2(25),
    -- Mo tai NH/KB (DM-BANK)
    RECEIVER_BANK_NAME          VARCHAR2(200),
    RECEIVER_ACCOUNT_NAME       VARCHAR2(200),
    RECEIVER_ID_NUMBER          VARCHAR2(20),
    RECEIVER_ID_ISSUE_DATE      DATE,
    RECEIVER_ID_ISSUE_PLACE     VARCHAR2(100),

    -- === Nhom 5: Workflow — Maker/Checker/Approver (BIZ-MAKER-CHECKER, BIZ-SOD) ===
    -- Nguoi lap (Maker)
    MAKER_ID                    VARCHAR2(50)    NOT NULL,
    MAKER_NAME                  VARCHAR2(200),
    -- Nguoi kiem soat (Checker)
    CHECKER_ID                  VARCHAR2(50),
    CHECKER_NAME                VARCHAR2(200),
    -- Nguoi phe duyet (Approver)
    APPROVER_ID                 VARCHAR2(50),
    APPROVER_NAME               VARCHAR2(200),
    -- Thoi gian kiem soat / phe duyet
    CHECKED_AT                  TIMESTAMP,
    APPROVED_AT                 TIMESTAMP,
    -- Ly do tu choi / huy (BIZ-REJECT-REASON: 10-500 ky tu)
    REJECT_REASON               VARCHAR2(500),
    REJECTED_BY                 VARCHAR2(50),
    REJECTED_AT                 TIMESTAMP,
    -- Ly do huy
    CANCEL_REASON               VARCHAR2(500),
    CANCELLED_BY                VARCHAR2(50),
    CANCELLED_AT                TIMESTAMP,

    -- === Nhom 6: Tich hop he thong ngoai ===
    -- Don vi KBNN xu ly
    UNIT_CODE                   VARCHAR2(10)    NOT NULL,
    -- Ngay lam viec he thong
    WORKING_DATE                DATE            NOT NULL,
    -- Ma but toan GL (sau khi hach toan thanh cong)
    GL_VOUCHER_NO               VARCHAR2(30),
    -- So tham chieu tu NHNN/NHTM (callback correlation)
    EXT_REFERENCE               VARCHAR2(50),
    -- Ma LTT dao (neu LTT nay la but toan dao cua LTT khac)
    REVERSAL_OF_ID              NUMBER(20),
    -- So lan gui / retry (BIZ-RETRY: toi da 3 lan)
    SEND_RETRY_COUNT            NUMBER(3)       DEFAULT 0,
    -- Ma correlation cho idempotency gateway
    CORRELATION_ID              VARCHAR2(64),

    -- === Nhom 7: Soft-delete (BIZ-DELETE-SOFT) ===
    IS_DELETED                  NUMBER(1)       DEFAULT 0 NOT NULL,
    DELETED_BY                  VARCHAR2(50),
    DELETED_AT                  TIMESTAMP,
    DELETE_REASON               VARCHAR2(500),

    -- === Nhom 8: Optimistic lock (BIZ-OPTIMISTIC-LOCK) ===
    VERSION                     NUMBER(10)      DEFAULT 1 NOT NULL,

    -- === Nhom 9: Audit columns ===
    CREATED_BY                  VARCHAR2(50)    NOT NULL,
    CREATED_AT                  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY                  VARCHAR2(50),
    UPDATED_AT                  TIMESTAMP       DEFAULT SYSTIMESTAMP,
    -- Dia chi IP nguoi thao tac cuoi
    LAST_IP_ADDRESS             VARCHAR2(45),

    -- === Nhom 10: Metadata ===
    -- Nguon tao: MANUAL (thu cong), COPY (sao chep), REVERSE (dao)
    SOURCE_TYPE                 VARCHAR2(10)    DEFAULT 'MANUAL',
    -- ID cua LTT goc (dung khi sao chep hoac dao)
    SOURCE_LTT_ID               NUMBER(20),

    -- === Rang buoc khoa chinh ===
    CONSTRAINT PK_LTT PRIMARY KEY (ID),

    -- === Rang buoc CHECK ===
    -- Trang thai phai nam trong 15 trang thai (states.yaml)
    CONSTRAINT CK_LTT_STATE CHECK (STATE IN (
        'DRAFT', 'SUBMITTED', 'IN_CONTROL', 'RETURNED_TO_MAKER',
        'RETURNED_TO_CHECKER', 'APPROVED', 'SIGNED', 'SENT',
        'SEND_FAILED', 'CONFIRMED', 'POSTED', 'POST_FAILED',
        'CANCELLED', 'REVERSED', 'BLOCKED'
    )),

    -- Kenh thanh toan (DM-CHANNEL)
    CONSTRAINT CK_LTT_CHANNEL CHECK (CHANNEL IN ('LNH', 'SP', 'LKB')),

    -- So tien > 0 (VAL-014)
    CONSTRAINT CK_LTT_AMOUNT CHECK (AMOUNT > 0),

    -- Soft-delete flag
    CONSTRAINT CK_LTT_IS_DELETED CHECK (IS_DELETED IN (0, 1)),

    -- Version >= 1
    CONSTRAINT CK_LTT_VERSION CHECK (VERSION >= 1),

    -- Ty gia > 0 khi co gia tri (VAL-016)
    CONSTRAINT CK_LTT_EXCHANGE_RATE CHECK (EXCHANGE_RATE IS NULL OR EXCHANGE_RATE > 0),

    -- Maker-Checker-Approver phai khac nhau (SoD: BIZ-MAKER-CHECKER, BIZ-SOD)
    -- Checker va Maker khong duoc trung nhau khi Checker da thuc hien
    CONSTRAINT CK_LTT_MAKER_CHECKER CHECK (
        CHECKER_ID IS NULL OR CHECKER_ID != MAKER_ID
    ),
    -- Approver va Checker khong duoc trung nhau khi ca hai da thuc hien
    CONSTRAINT CK_LTT_CHECKER_APPROVER CHECK (
        APPROVER_ID IS NULL OR CHECKER_ID IS NULL OR APPROVER_ID != CHECKER_ID
    ),
    -- Approver va Maker khong duoc trung nhau khi Approver da thuc hien
    CONSTRAINT CK_LTT_MAKER_APPROVER CHECK (
        APPROVER_ID IS NULL OR APPROVER_ID != MAKER_ID
    ),

    -- So lan retry >= 0
    CONSTRAINT CK_LTT_RETRY_COUNT CHECK (SEND_RETRY_COUNT >= 0),

    -- Loai tien theo ISO-4217 (3 ky tu)
    CONSTRAINT CK_LTT_CURRENCY CHECK (REGEXP_LIKE(CURRENCY, '^[A-Z]{3}$')),

    -- Nguon tao
    CONSTRAINT CK_LTT_SOURCE_TYPE CHECK (SOURCE_TYPE IN ('MANUAL', 'COPY', 'REVERSE'))
);

-- === Comments cho bang LTT ===
COMMENT ON TABLE  LTT IS 'Lenh thanh toan di NHNN thu cong — ban ghi chinh';
COMMENT ON COLUMN LTT.ID IS 'Khoa chinh tu tang';
COMMENT ON COLUMN LTT.SO_YCTT IS 'So yeu cau thanh toan / So but toan — dinh danh duy nhat theo kenh (BIZ-IDGEN)';
COMMENT ON COLUMN LTT.IDEMPOTENCY_KEY IS 'Ma dinh danh duy nhat cho moi REST POST / MQ message (ADR idempotency)';
COMMENT ON COLUMN LTT.STATE IS 'Trang thai LTT — 15 gia tri theo states.yaml';
COMMENT ON COLUMN LTT.PREV_STATE IS 'Trang thai truoc khi bi BLOCK — de UNBLOCK quay lai trang thai cu';
COMMENT ON COLUMN LTT.CHANNEL IS 'Kenh thanh toan: LNH (Lien ngan hang), SP (Song phuong), LKB (Lien kho bac)';
COMMENT ON COLUMN LTT.ORDER_TYPE IS 'Loai lenh thanh toan (DM-ORDER-TYPE): OT-LNH-LCC, OT-SP-CK, ...';
COMMENT ON COLUMN LTT.SENDER_BANK_CODE IS 'Ma NH/KB chuyen — 8 ky tu BIN (DM-BANK)';
COMMENT ON COLUMN LTT.RECEIVER_BANK_CODE IS 'Ma NH/KB nhan — 8 ky tu BIN (DM-BANK)';
COMMENT ON COLUMN LTT.PAYMENT_DATE IS 'Ngay thanh toan — khong nho hon ngay lam viec (VAL-012)';
COMMENT ON COLUMN LTT.AMOUNT IS 'So tien chuyen (VND hoac quy doi) — phai > 0 (VAL-014)';
COMMENT ON COLUMN LTT.CURRENCY IS 'Loai tien ISO-4217 — mac dinh VND';
COMMENT ON COLUMN LTT.TXN_TYPE IS 'Loai giao dich chi kenh LNH (DM-TXN-TYPE: TX-LCC, TX-LCT, ...)';
COMMENT ON COLUMN LTT.EXCHANGE_RATE IS 'Ty gia ngoai te — bat buoc khi loai tien khac VND (VAL-016)';
COMMENT ON COLUMN LTT.ORIG_DOC_NO IS 'So chung tu goc — bat buoc khi kenh SP (VAL-018)';
COMMENT ON COLUMN LTT.ORIG_DOC_DATE IS 'Ngay chung tu goc';
COMMENT ON COLUMN LTT.FEE_TYPE IS 'Loai phi (DM-FEE-TYPE): FE-OUR, FE-BEN, FE-SHA, FE-NONE, FE-NETOUT';
COMMENT ON COLUMN LTT.DEBIT_CCY IS 'Ma ngoai te trich no — bat buoc khi loai lenh ngoai te';
COMMENT ON COLUMN LTT.PAYMENT_CCY IS 'Ma ngoai te thanh toan — bat buoc khi loai lenh ngoai te';
COMMENT ON COLUMN LTT.PAYMENT_CCY_AMOUNT IS 'So tien ngoai te thanh toan';
COMMENT ON COLUMN LTT.PAYMENT_CONTENT IS 'Noi dung thanh toan — bat buoc nhap';
COMMENT ON COLUMN LTT.TPCP_CODE IS 'Ma Trai phieu Chinh phu — bat buoc khi loai lenh OT-SP-TPCP (VAL-027)';
COMMENT ON COLUMN LTT.COA_FUND IS 'Ma quy (DM-MAQUY) — 2 ky tu, mac dinh 01';
COMMENT ON COLUMN LTT.COA_NATURAL_ACCOUNT IS 'Tai khoan tu nhien (DM-TK) — 4 ky tu';
COMMENT ON COLUMN LTT.COA_DVQHNS IS 'Don vi quan he ngan sach (DM-DVQHNS) — 7 ky tu';
COMMENT ON COLUMN LTT.COA_BUDGET_LEVEL IS 'Cap ngan sach (DM-CAPNS) — 1 ky tu';
COMMENT ON COLUMN LTT.COA_CHAPTER IS 'Chuong (DM-CHUONG) — 3 ky tu, mac dinh 000';
COMMENT ON COLUMN LTT.COA_INDUSTRY IS 'Nganh kinh te (DM-NGANHKT) — 3 ky tu, mac dinh 000';
COMMENT ON COLUMN LTT.COA_NDKT IS 'Noi dung kinh te (DM-NDKT) — 4 ky tu, mac dinh 0000';
COMMENT ON COLUMN LTT.COA_AREA IS 'Dia ban (DM-DIABAN) — 5 ky tu, mac dinh 00000';
COMMENT ON COLUMN LTT.COA_PROGRAM IS 'Chuong trinh muc tieu (DM-CTMT) — 5 ky tu, mac dinh 00000';
COMMENT ON COLUMN LTT.COA_FUND_SOURCE IS 'Ma nguon kinh phi (DM-MN) — 2 ky tu, mac dinh 00';
COMMENT ON COLUMN LTT.COA_TREASURY IS 'Ma kho bac (DM-KB) — 4 ky tu, mac dinh 0000';
COMMENT ON COLUMN LTT.COA_RESERVE IS 'Ma du phong (DM-DP) — 3 ky tu, mac dinh 000';
COMMENT ON COLUMN LTT.SENDER_NAME IS 'Ten nguoi chuyen tien';
COMMENT ON COLUMN LTT.SENDER_ADDRESS IS 'Dia chi nguoi chuyen';
COMMENT ON COLUMN LTT.SENDER_ACCOUNT IS 'So tai khoan nguoi chuyen';
COMMENT ON COLUMN LTT.SENDER_CUSTOMER_CODE IS 'Ma khach hang nguoi chuyen';
COMMENT ON COLUMN LTT.SENDER_BANK_NAME IS 'Ten NH/KB mo tai cua nguoi chuyen';
COMMENT ON COLUMN LTT.SENDER_ID_NUMBER IS 'So CMND/CCCD/HC/Ma DN nguoi chuyen';
COMMENT ON COLUMN LTT.SENDER_ID_ISSUE_DATE IS 'Ngay cap CMND/CCCD/HC nguoi chuyen';
COMMENT ON COLUMN LTT.SENDER_ID_ISSUE_PLACE IS 'Noi cap CMND/CCCD/HC nguoi chuyen';
COMMENT ON COLUMN LTT.RECEIVER_NAME IS 'Ten nguoi nhan tien';
COMMENT ON COLUMN LTT.RECEIVER_ADDRESS IS 'Dia chi nguoi nhan';
COMMENT ON COLUMN LTT.RECEIVER_ACCOUNT IS 'So tai khoan nguoi nhan';
COMMENT ON COLUMN LTT.RECEIVER_BANK_NAME IS 'Ten NH/KB mo tai cua nguoi nhan';
COMMENT ON COLUMN LTT.RECEIVER_ACCOUNT_NAME IS 'Ten tai khoan nguoi nhan';
COMMENT ON COLUMN LTT.RECEIVER_ID_NUMBER IS 'So CMND/CCCD/HC/Ma DN nguoi nhan';
COMMENT ON COLUMN LTT.RECEIVER_ID_ISSUE_DATE IS 'Ngay cap CMND/CCCD/HC nguoi nhan';
COMMENT ON COLUMN LTT.RECEIVER_ID_ISSUE_PLACE IS 'Noi cap CMND/CCCD/HC nguoi nhan';
COMMENT ON COLUMN LTT.MAKER_ID IS 'Ma nguoi lap (Maker) — khong duoc sua (BIZ-EDIT-IMMUTABLE)';
COMMENT ON COLUMN LTT.MAKER_NAME IS 'Ten nguoi lap';
COMMENT ON COLUMN LTT.CHECKER_ID IS 'Ma nguoi kiem soat (Checker) — phai khac Maker (SOD-001)';
COMMENT ON COLUMN LTT.CHECKER_NAME IS 'Ten nguoi kiem soat';
COMMENT ON COLUMN LTT.APPROVER_ID IS 'Ma nguoi phe duyet (Approver) — phai khac Checker va Maker (SOD-002, SOD-003)';
COMMENT ON COLUMN LTT.APPROVER_NAME IS 'Ten nguoi phe duyet';
COMMENT ON COLUMN LTT.CHECKED_AT IS 'Thoi gian kiem soat';
COMMENT ON COLUMN LTT.APPROVED_AT IS 'Thoi gian phe duyet';
COMMENT ON COLUMN LTT.REJECT_REASON IS 'Ly do tu choi — bat buoc >= 10 ky tu (BIZ-REJECT-REASON, VAL-030)';
COMMENT ON COLUMN LTT.REJECTED_BY IS 'Ma nguoi tu choi';
COMMENT ON COLUMN LTT.REJECTED_AT IS 'Thoi gian tu choi';
COMMENT ON COLUMN LTT.CANCEL_REASON IS 'Ly do huy — bat buoc >= 10 ky tu (BIZ-REJECT-REASON)';
COMMENT ON COLUMN LTT.CANCELLED_BY IS 'Ma nguoi huy';
COMMENT ON COLUMN LTT.CANCELLED_AT IS 'Thoi gian huy';
COMMENT ON COLUMN LTT.UNIT_CODE IS 'Ma don vi KBNN xu ly';
COMMENT ON COLUMN LTT.WORKING_DATE IS 'Ngay lam viec he thong';
COMMENT ON COLUMN LTT.GL_VOUCHER_NO IS 'Ma but toan GL — cap sau khi hach toan thanh cong';
COMMENT ON COLUMN LTT.EXT_REFERENCE IS 'Ma tham chieu tu NHNN/NHTM (correlation)';
COMMENT ON COLUMN LTT.REVERSAL_OF_ID IS 'ID LTT goc khi LTT nay la but toan dao';
COMMENT ON COLUMN LTT.SEND_RETRY_COUNT IS 'So lan gui lai — toi da 3 (BIZ-RETRY)';
COMMENT ON COLUMN LTT.CORRELATION_ID IS 'Ma correlation cho idempotency gateway gui NH';
COMMENT ON COLUMN LTT.IS_DELETED IS 'Danh dau xoa mem (soft-delete) — 0: chua xoa, 1: da xoa (BIZ-DELETE-SOFT)';
COMMENT ON COLUMN LTT.DELETED_BY IS 'Nguoi thuc hien xoa mem';
COMMENT ON COLUMN LTT.DELETED_AT IS 'Thoi gian xoa mem';
COMMENT ON COLUMN LTT.DELETE_REASON IS 'Ly do xoa — bat buoc >= 10 ky tu (BIZ-DELETE-DRAFT)';
COMMENT ON COLUMN LTT.VERSION IS 'Phien ban cho optimistic lock — tang moi lan cap nhat (BIZ-OPTIMISTIC-LOCK)';
COMMENT ON COLUMN LTT.CREATED_BY IS 'Nguoi tao ban ghi';
COMMENT ON COLUMN LTT.CREATED_AT IS 'Thoi gian tao ban ghi';
COMMENT ON COLUMN LTT.UPDATED_BY IS 'Nguoi cap nhat cuoi cung';
COMMENT ON COLUMN LTT.UPDATED_AT IS 'Thoi gian cap nhat cuoi cung';
COMMENT ON COLUMN LTT.LAST_IP_ADDRESS IS 'Dia chi IP cua nguoi thao tac cuoi';
COMMENT ON COLUMN LTT.SOURCE_TYPE IS 'Nguon tao: MANUAL, COPY, REVERSE';
COMMENT ON COLUMN LTT.SOURCE_LTT_ID IS 'ID LTT goc khi sao chep hoac dao';

-- === Index cho bang LTT ===
-- Tim kiem theo trang thai (S01, S04)
CREATE INDEX IDX_LTT_STATE ON LTT (STATE);

-- Tim kiem theo kenh (S01)
CREATE INDEX IDX_LTT_CHANNEL ON LTT (CHANNEL);

-- Tim kiem theo ngay thanh toan (S01 — sort mac dinh giam dan)
CREATE INDEX IDX_LTT_PAYMENT_DATE ON LTT (PAYMENT_DATE DESC);

-- Tim kiem theo nguoi lap (BIZ-EDIT-OWN, VAL-032)
CREATE INDEX IDX_LTT_MAKER_ID ON LTT (MAKER_ID);

-- Idempotency — da co UNIQUE constraint tu dong tao index

-- Tim kiem theo so YCTT
CREATE INDEX IDX_LTT_SO_YCTT ON LTT (SO_YCTT);

-- Tim kiem theo don vi + ngay lam viec (VAL-010: trung so YCTT)
CREATE INDEX IDX_LTT_UNIT_WORKDATE ON LTT (UNIT_CODE, WORKING_DATE);

-- Tim kiem theo NH nhan
CREATE INDEX IDX_LTT_RECEIVER_BANK ON LTT (RECEIVER_BANK_CODE);

-- Tim kiem theo trang thai + ngay tao (hang doi S04)
CREATE INDEX IDX_LTT_STATE_CREATED ON LTT (STATE, CREATED_AT DESC);

-- Composite index cho tim kiem danh sach S01 (kenh + trang thai + ngay)
CREATE INDEX IDX_LTT_CH_STA_DATE ON LTT (CHANNEL, STATE, PAYMENT_DATE DESC);

-- Soft-delete — loc ban ghi chua xoa
CREATE INDEX IDX_LTT_NOT_DELETED ON LTT (IS_DELETED, UNIT_CODE);

-- Correlation id cho gateway NHNN
CREATE INDEX IDX_LTT_CORRELATION ON LTT (CORRELATION_ID);

-- Reverse lookup
CREATE INDEX IDX_LTT_REVERSAL_OF ON LTT (REVERSAL_OF_ID);


-- ============================================================================
-- Bang LTT_LINE_ITEM — Chi tiet khoan muc COA (nhieu dong)
-- Moi dong la mot to hop COA day du theo coa-segments.yaml
-- ============================================================================
CREATE TABLE LTT_LINE_ITEM (
    ID                  NUMBER(20)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LTT_ID              NUMBER(20)  NOT NULL,
    LINE_NO             NUMBER(5)   NOT NULL,

    -- 11 COA segments (coa-segments.yaml)
    COA_FUND            VARCHAR2(2)     DEFAULT '01',
    COA_NATURAL_ACCOUNT VARCHAR2(4),
    COA_DVQHNS          VARCHAR2(7),
    COA_BUDGET_LEVEL    VARCHAR2(1),
    COA_CHAPTER         VARCHAR2(3)     DEFAULT '000',
    COA_INDUSTRY        VARCHAR2(3)     DEFAULT '000',
    COA_NDKT            VARCHAR2(4)     DEFAULT '0000',
    COA_AREA            VARCHAR2(5)     DEFAULT '00000',
    COA_PROGRAM         VARCHAR2(5)     DEFAULT '00000',
    COA_FUND_SOURCE     VARCHAR2(2)     DEFAULT '00',
    COA_TREASURY        VARCHAR2(4)     DEFAULT '0000',
    COA_RESERVE         VARCHAR2(3)     DEFAULT '000',

    -- Dien giai khoan muc
    DESCRIPTION         VARCHAR2(250)   NOT NULL,
    -- So tien chi tiet tung dong
    LINE_AMOUNT         NUMBER(18,2)    NOT NULL,

    -- Audit
    CREATED_BY          VARCHAR2(50)    NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(50),
    UPDATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP,

    CONSTRAINT PK_LTT_LINE_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_LTT_LINE_ITEM_LTT FOREIGN KEY (LTT_ID)
        REFERENCES LTT (ID) ON DELETE CASCADE,
    CONSTRAINT CK_LTT_LINE_AMOUNT CHECK (LINE_AMOUNT > 0),
    CONSTRAINT CK_LTT_LINE_NO CHECK (LINE_NO > 0),
    CONSTRAINT UQ_LTT_LINE_ITEM UNIQUE (LTT_ID, LINE_NO)
);

COMMENT ON TABLE  LTT_LINE_ITEM IS 'Chi tiet khoan muc COA cua LTT — moi dong la mot to hop COA day du';
COMMENT ON COLUMN LTT_LINE_ITEM.LTT_ID IS 'FK ve bang LTT';
COMMENT ON COLUMN LTT_LINE_ITEM.LINE_NO IS 'Thu tu dong khoan muc';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_FUND IS 'Ma quy (DM-MAQUY) — 2 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_NATURAL_ACCOUNT IS 'Tai khoan tu nhien (DM-TK) — 4 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_DVQHNS IS 'Don vi quan he ngan sach (DM-DVQHNS) — 7 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_BUDGET_LEVEL IS 'Cap ngan sach (DM-CAPNS) — 1 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_CHAPTER IS 'Chuong (DM-CHUONG) — 3 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_INDUSTRY IS 'Nganh kinh te (DM-NGANHKT) — 3 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_NDKT IS 'Noi dung kinh te (DM-NDKT) — 4 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_AREA IS 'Dia ban (DM-DIABAN) — 5 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_PROGRAM IS 'Chuong trinh muc tieu (DM-CTMT) — 5 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_FUND_SOURCE IS 'Ma nguon kinh phi (DM-MN) — 2 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_TREASURY IS 'Ma kho bac (DM-KB) — 4 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.COA_RESERVE IS 'Ma du phong (DM-DP) — 3 ky tu';
COMMENT ON COLUMN LTT_LINE_ITEM.DESCRIPTION IS 'Dien giai khoan muc — toi da 250 ky tu (VAL-023)';
COMMENT ON COLUMN LTT_LINE_ITEM.LINE_AMOUNT IS 'So tien chi tiet dong khoan muc — phai > 0 (VAL-015)';

CREATE INDEX IDX_LTT_LINE_LTT_ID ON LTT_LINE_ITEM (LTT_ID);


-- ============================================================================
-- Bang LTT_ATTACHMENT — Dinh kem chung tu (VAL-029)
-- ============================================================================
CREATE TABLE LTT_ATTACHMENT (
    ID                  NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LTT_ID              NUMBER(20)      NOT NULL,
    -- Ten file goc
    FILE_NAME           VARCHAR2(255)   NOT NULL,
    -- Dinh dang file: pdf, jpg, png, docx (VAL-029)
    FILE_TYPE           VARCHAR2(10)    NOT NULL,
    -- Kich thuoc file (bytes) — toi da 10MB (VAL-029)
    FILE_SIZE           NUMBER(10)      NOT NULL,
    -- Duong dan luu tru ECM / local
    STORAGE_PATH        VARCHAR2(500),
    -- Hash SHA-256 cua file (BIZ-SIGN-TAD-COMM)
    FILE_HASH           VARCHAR2(64),
    -- Mo ta chung tu
    DESCRIPTION         VARCHAR2(500),

    -- Audit
    UPLOADED_BY         VARCHAR2(50)    NOT NULL,
    UPLOADED_AT         TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_LTT_ATTACHMENT PRIMARY KEY (ID),
    CONSTRAINT FK_LTT_ATTACHMENT_LTT FOREIGN KEY (LTT_ID)
        REFERENCES LTT (ID) ON DELETE CASCADE,
    CONSTRAINT CK_LTT_FILE_SIZE CHECK (FILE_SIZE > 0 AND FILE_SIZE <= 10485760),
    CONSTRAINT CK_LTT_FILE_TYPE CHECK (LOWER(FILE_TYPE) IN ('pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'))
);

COMMENT ON TABLE  LTT_ATTACHMENT IS 'Chung tu dinh kem cua LTT — gioi han 10MB/file (VAL-029)';
COMMENT ON COLUMN LTT_ATTACHMENT.LTT_ID IS 'FK ve bang LTT';
COMMENT ON COLUMN LTT_ATTACHMENT.FILE_NAME IS 'Ten file goc';
COMMENT ON COLUMN LTT_ATTACHMENT.FILE_TYPE IS 'Dinh dang file: pdf, jpg, jpeg, png, doc, docx';
COMMENT ON COLUMN LTT_ATTACHMENT.FILE_SIZE IS 'Kich thuoc file (bytes) — toi da 10MB';
COMMENT ON COLUMN LTT_ATTACHMENT.STORAGE_PATH IS 'Duong dan luu tru ECM';
COMMENT ON COLUMN LTT_ATTACHMENT.FILE_HASH IS 'Hash SHA-256 cua file';
COMMENT ON COLUMN LTT_ATTACHMENT.DESCRIPTION IS 'Mo ta chung tu';

CREATE INDEX IDX_LTT_ATTACH_LTT_ID ON LTT_ATTACHMENT (LTT_ID);


-- ============================================================================
-- Bang LTT_AUDIT — Nhat ky kiem toan (BIZ-AUDIT, BIZ-EDIT-AUDIT)
-- Ghi moi thao tac: create, update, submit, approve, reject, cancel, sign, send
-- ============================================================================
CREATE TABLE LTT_AUDIT (
    ID                  NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LTT_ID              NUMBER(20)      NOT NULL,
    -- Hanh dong: CREATE, EDIT, SUBMIT, APPROVE_CHECK, APPROVE, REJECT,
    --            CANCEL, SIGN, SEND, CONFIRM, REVERSE, DELETE, BLOCK, UNBLOCK
    ACTION              VARCHAR2(30)    NOT NULL,
    -- Trang thai truoc thao tac
    STATE_FROM          VARCHAR2(25),
    -- Trang thai sau thao tac
    STATE_TO            VARCHAR2(25),
    -- Nguoi thuc hien
    PERFORMED_BY        VARCHAR2(50)    NOT NULL,
    PERFORMED_BY_NAME   VARCHAR2(200),
    -- Thoi gian thuc hien
    PERFORMED_AT        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    -- Dia chi IP
    IP_ADDRESS          VARCHAR2(45),
    -- Phien ban truoc/sau (optimistic lock)
    VERSION_FROM        NUMBER(10),
    VERSION_TO          NUMBER(10),
    -- Diff cap truong JSON — {field, oldValue, newValue} (BIZ-EDIT-AUDIT)
    FIELD_DIFFS         CLOB,
    -- Thong tin them (ly do tu choi, ly do huy, ...)
    REASON              VARCHAR2(500),
    -- Thong tin them dang JSON
    METADATA            CLOB,

    CONSTRAINT PK_LTT_AUDIT PRIMARY KEY (ID),
    CONSTRAINT FK_LTT_AUDIT_LTT FOREIGN KEY (LTT_ID)
        REFERENCES LTT (ID) ON DELETE CASCADE
);

COMMENT ON TABLE  LTT_AUDIT IS 'Nhat ky kiem toan LTT — ghi moi thao tac (BIZ-AUDIT)';
COMMENT ON COLUMN LTT_AUDIT.LTT_ID IS 'FK ve bang LTT';
COMMENT ON COLUMN LTT_AUDIT.ACTION IS 'Hanh dong: CREATE, EDIT, SUBMIT, APPROVE_CHECK, APPROVE, REJECT, CANCEL, SIGN, SEND, CONFIRM, REVERSE, DELETE, BLOCK, UNBLOCK';
COMMENT ON COLUMN LTT_AUDIT.STATE_FROM IS 'Trang thai truoc thao tac';
COMMENT ON COLUMN LTT_AUDIT.STATE_TO IS 'Trang thai sau thao tac';
COMMENT ON COLUMN LTT_AUDIT.PERFORMED_BY IS 'Ma nguoi thuc hien thao tac';
COMMENT ON COLUMN LTT_AUDIT.PERFORMED_BY_NAME IS 'Ten nguoi thuc hien thao tac';
COMMENT ON COLUMN LTT_AUDIT.PERFORMED_AT IS 'Thoi gian thuc hien thao tac';
COMMENT ON COLUMN LTT_AUDIT.IP_ADDRESS IS 'Dia chi IP cua nguoi thuc hien';
COMMENT ON COLUMN LTT_AUDIT.VERSION_FROM IS 'Phien ban truoc thao tac (optimistic lock)';
COMMENT ON COLUMN LTT_AUDIT.VERSION_TO IS 'Phien ban sau thao tac (optimistic lock)';
COMMENT ON COLUMN LTT_AUDIT.FIELD_DIFFS IS 'Diff cap truong JSON — mang [{field, oldValue, newValue}] (BIZ-EDIT-AUDIT)';
COMMENT ON COLUMN LTT_AUDIT.REASON IS 'Ly do tu choi / huy / xoa';
COMMENT ON COLUMN LTT_AUDIT.METADATA IS 'Thong tin bo sung dang JSON';

CREATE INDEX IDX_LTT_AUDIT_LTT_ID ON LTT_AUDIT (LTT_ID, PERFORMED_AT DESC);
CREATE INDEX IDX_LTT_AUDIT_ACTION ON LTT_AUDIT (ACTION);
CREATE INDEX IDX_LTT_AUDIT_PERFORMED ON LTT_AUDIT (PERFORMED_BY, PERFORMED_AT DESC);


-- ============================================================================
-- Bang LTT_SIGNATURE — Chu ky so (BIZ-SIGN-TAD-COMM)
-- ============================================================================
CREATE TABLE LTT_SIGNATURE (
    ID                      NUMBER(20)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LTT_ID                  NUMBER(20)  NOT NULL,
    -- Nguoi ky
    SIGNER_ID               VARCHAR2(50)    NOT NULL,
    SIGNER_NAME             VARCHAR2(200),
    -- Vai tro ky: APPROVER
    SIGNER_ROLE              VARCHAR2(20)    NOT NULL,
    -- Loai chu ky: DIGITAL (ky so)
    SIGN_TYPE               VARCHAR2(10)    DEFAULT 'DIGITAL' NOT NULL,
    -- Chu ky so (base64 hoac duong dan ECM)
    SIGNATURE_DATA          CLOB,
    -- Chung thu so (certificate)
    CERTIFICATE_SERIAL      VARCHAR2(100),
    -- Thoi gian ky
    SIGNED_AT               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    -- Hash SHA-256 cua noi dung ky
    CONTENT_HASH            VARCHAR2(64)    NOT NULL,
    -- Trang thai chu ky: VALID, INVALID, EXPIRED, REVOKED
    SIGN_STATUS             VARCHAR2(10)    DEFAULT 'VALID' NOT NULL,
    -- Duong dan luu ECM
    ECM_DOC_ID              VARCHAR2(100),

    CONSTRAINT PK_LTT_SIGNATURE PRIMARY KEY (ID),
    CONSTRAINT FK_LTT_SIGNATURE_LTT FOREIGN KEY (LTT_ID)
        REFERENCES LTT (ID) ON DELETE CASCADE,
    CONSTRAINT CK_LTT_SIGN_STATUS CHECK (SIGN_STATUS IN ('VALID', 'INVALID', 'EXPIRED', 'REVOKED')),
    CONSTRAINT CK_LTT_SIGN_TYPE CHECK (SIGN_TYPE IN ('DIGITAL'))
);

COMMENT ON TABLE  LTT_SIGNATURE IS 'Chu ky so cua LTT — ky boi Approver (BIZ-SIGN-TAD-COMM)';
COMMENT ON COLUMN LTT_SIGNATURE.LTT_ID IS 'FK ve bang LTT';
COMMENT ON COLUMN LTT_SIGNATURE.SIGNER_ID IS 'Ma nguoi ky so';
COMMENT ON COLUMN LTT_SIGNATURE.SIGNER_NAME IS 'Ten nguoi ky so';
COMMENT ON COLUMN LTT_SIGNATURE.SIGNER_ROLE IS 'Vai tro nguoi ky: APPROVER';
COMMENT ON COLUMN LTT_SIGNATURE.SIGN_TYPE IS 'Loai chu ky: DIGITAL';
COMMENT ON COLUMN LTT_SIGNATURE.SIGNATURE_DATA IS 'Du lieu chu ky so (base64 hoac XML)';
COMMENT ON COLUMN LTT_SIGNATURE.CERTIFICATE_SERIAL IS 'So seri chung thu so';
COMMENT ON COLUMN LTT_SIGNATURE.SIGNED_AT IS 'Thoi gian ky so';
COMMENT ON COLUMN LTT_SIGNATURE.CONTENT_HASH IS 'Hash SHA-256 noi dung LTT tai thoi diem ky';
COMMENT ON COLUMN LTT_SIGNATURE.SIGN_STATUS IS 'Trang thai chu ky: VALID, INVALID, EXPIRED, REVOKED';
COMMENT ON COLUMN LTT_SIGNATURE.ECM_DOC_ID IS 'Ma tai lieu ECM — luu chu ky vao he thong quan ly chung tu';

CREATE INDEX IDX_LTT_SIGN_LTT_ID ON LTT_SIGNATURE (LTT_ID);


-- ============================================================================
-- Trigger tu dong cap nhat UPDATED_AT khi sua LTT
-- ============================================================================
CREATE OR REPLACE TRIGGER TRG_LTT_UPD_TIMESTAMP
BEFORE UPDATE ON LTT
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
    -- Tang version cho optimistic lock
    IF :NEW.VERSION = :OLD.VERSION THEN
        :NEW.VERSION := :OLD.VERSION + 1;
    END IF;
END;
/


-- ============================================================================
-- Trigger tu dong cap nhat UPDATED_AT khi sua LTT_LINE_ITEM
-- ============================================================================
CREATE OR REPLACE TRIGGER TRG_LTT_LINE_ITEM_UPD
BEFORE UPDATE ON LTT_LINE_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/
