-- ============================================================================
-- V2__outbox.sql — Mau hinh Outbox cho atomic DB write + MQ publish
-- Module: TT.OUT.MANUAL — Lenh thanh toan di NHNN thu cong
-- Oracle 19c DDL
-- Generated: 2026-05-10 | SA + DBA — Stage 2
-- Reference: CLAUDE.md (Outbox pattern), events.yaml (BIZ-EVENT-PUBLISH),
--            CONTEXT.md (MQ channels: LNH/SP/LKB)
-- ============================================================================
--
-- Nguyen ly: Ghi du lieu vao DB va day tin nhan vao hang doi trong CUNG MOT
-- giao dich Oracle. Outbox table luu event truoc khi publish len IBM MQ.
-- Mot process rieng (polling-based hoac Oracle AQ notification) se doc tu
-- outbox va publish len MQ.
--
-- Luong:
--   1. Application ghi LTT + OUTBOX trong cung 1 transaction
--   2. Outbox poller (hoac AQ subscriber) doc PENDING events
--   3. Publish len IBM MQ (LNH.SEND.Q / SP.SEND.Q / LKB.SEND.Q)
--   4. Danh dau PUBLISHED hoac FAILED
--   5. Retry neu FAILED (toi da 3 lan, BIZ-RETRY)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Sequence cho OUTBOX
-- ---------------------------------------------------------------------------
-- Su dung IDENTITY column thay vi sequence rieng (Oracle 19c)

-- ---------------------------------------------------------------------------
-- Bang OUTBOX — Luu event truoc khi publish len MQ
-- ---------------------------------------------------------------------------
CREATE TABLE OUTBOX (
    -- Khoa chinh
    ID                      NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Loai aggregate (ten bang): LTT, LTT_LINE_ITEM, ...
    AGGREGATE_TYPE          VARCHAR2(50)    NOT NULL,

    -- ID cua aggregate (FK logic, khong dung FK vat ly de giam coupling)
    AGGREGATE_ID            NUMBER(20)      NOT NULL,

    -- Loai su kien — tu events.yaml va states.yaml transitions
    -- Vi du: LTT_CREATED, LTT_SUBMITTED, LTT_APPROVED_CHECK, LTT_APPROVED,
    --        LTT_REJECTED, LTT_CANCELLED, LTT_SIGNED, LTT_SENT,
    --        LTT_CONFIRMED, LTT_POSTED, LTT_REVERSED, LTT_BLOCKED, LTT_UNBLOCKED
    EVENT_TYPE              VARCHAR2(50)    NOT NULL,

    -- Noi dung event dang JSON (Oracle 19c ho tro JSON type)
    -- Su dung CLOB voi IS JSON constraint de dam bao tinh hop le
    PAYLOAD                 CLOB            NOT NULL,

    -- Trang thai xu ly: PENDING, PUBLISHED, FAILED
    STATUS                  VARCHAR2(15)    DEFAULT 'PENDING' NOT NULL,

    -- So lan da thu publish
    RETRY_COUNT             NUMBER(3)       DEFAULT 0 NOT NULL,

    -- So lan thu toi da (mac dinh 3 theo BIZ-RETRY)
    MAX_RETRIES             NUMBER(3)       DEFAULT 3 NOT NULL,

    -- Thoi gian tao event
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Thoi gian publish thanh cong
    PUBLISHED_AT            TIMESTAMP,

    -- Thoi gian xu ly tiep theo (cho retry voi backoff)
    NEXT_RETRY_AT           TIMESTAMP,

    -- Loi khi publish (neu FAILED)
    ERROR_MESSAGE           VARCHAR2(4000),

    -- Ma correlation — dung cho idempotency gateway (BIZ-RETRY)
    CORRELATION_ID          VARCHAR2(64),

    -- Kenh dich: LNH, SP, LKB (de dinh tuyen MQ queue)
    TARGET_CHANNEL          VARCHAR2(5),

    -- Ten MQ queue dich
    TARGET_QUEUE            VARCHAR2(50),

    -- Partition key (dung cho scale-out polling)
    PARTITION_KEY           VARCHAR2(50),

    -- Idempotency key — dam bao event khong bi xu ly 2 lan
    IDEMPOTENCY_KEY         VARCHAR2(64)    UNIQUE,

    -- Thong tin nguoi tao event
    CREATED_BY              VARCHAR2(50)    NOT NULL,

    -- === Constraints ===
    CONSTRAINT PK_OUTBOX PRIMARY KEY (ID),
    CONSTRAINT CK_OUTBOX_STATUS CHECK (STATUS IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT CK_OUTBOX_RETRY CHECK (RETRY_COUNT >= 0 AND RETRY_COUNT <= MAX_RETRIES),
    CONSTRAINT CK_OUTBOX_CHANNEL CHECK (TARGET_CHANNEL IS NULL OR TARGET_CHANNEL IN ('LNH', 'SP', 'LKB')),
    CONSTRAINT CK_OUTBOX_PAYLOAD_JSON CHECK (PAYLOAD IS JSON)
);

-- === Comments cho bang OUTBOX ===
COMMENT ON TABLE  OUTBOX IS 'Outbox pattern — luu event truoc khi publish len IBM MQ (atomically trong cung giao dich DB)';
COMMENT ON COLUMN OUTBOX.ID IS 'Khoa chinh tu tang';
COMMENT ON COLUMN OUTBOX.AGGREGATE_TYPE IS 'Loai aggregate: LTT, LTT_LINE_ITEM, ...';
COMMENT ON COLUMN OUTBOX.AGGREGATE_ID IS 'ID cua aggregate (FK logic)';
COMMENT ON COLUMN OUTBOX.EVENT_TYPE IS 'Loai su kien — vi du: LTT_CREATED, LTT_SUBMITTED, LTT_APPROVED, ...';
COMMENT ON COLUMN OUTBOX.PAYLOAD IS 'Noi dung event dang JSON — Oracle 19c JSON';
COMMENT ON COLUMN OUTBOX.STATUS IS 'Trang thai xu ly: PENDING (cho xu ly), PUBLISHED (da gui), FAILED (loi)';
COMMENT ON COLUMN OUTBOX.RETRY_COUNT IS 'So lan da thu publish';
COMMENT ON COLUMN OUTBOX.MAX_RETRIES IS 'So lan thu toi da — mac dinh 3 (BIZ-RETRY)';
COMMENT ON COLUMN OUTBOX.CREATED_AT IS 'Thoi gian tao event';
COMMENT ON COLUMN OUTBOX.PUBLISHED_AT IS 'Thoi gian publish thanh cong len MQ';
COMMENT ON COLUMN OUTBOX.NEXT_RETRY_AT IS 'Thoi gian xu ly tiep theo (backoff: 5s, 15s, 45s)';
COMMENT ON COLUMN OUTBOX.ERROR_MESSAGE IS 'Thong bao loi khi publish that bai';
COMMENT ON COLUMN OUTBOX.CORRELATION_ID IS 'Ma correlation cho idempotency gateway (BIZ-RETRY)';
COMMENT ON COLUMN OUTBOX.TARGET_CHANNEL IS 'Kenh dich: LNH, SP, LKB — de chon MQ queue';
COMMENT ON COLUMN OUTBOX.TARGET_QUEUE IS 'Ten MQ queue dich — vi du: LNH.SEND.Q, SP.SEND.Q, LKB.SEND.Q';
COMMENT ON COLUMN OUTBOX.PARTITION_KEY IS 'Partition key cho scale-out polling';
COMMENT ON COLUMN OUTBOX.IDEMPOTENCY_KEY IS 'Ma dinh danh duy nhat — dam bao event khong bi xu ly 2 lan';
COMMENT ON COLUMN OUTBOX.CREATED_BY IS 'Ma nguoi tao event';

-- === Index cho bang OUTBOX ===
-- Index chinh cho polling: lay PENDING events sap xep theo thoi gian tao
CREATE INDEX IDX_OUTBOX_POLL ON OUTBOX (STATUS, CREATED_AT)
    COMPRESS 1;

-- Index cho retry: lay FAILED events da den thoi gian retry
CREATE INDEX IDX_OUTBOX_RETRY ON OUTBOX (STATUS, NEXT_RETRY_AT)
    WHERE STATUS = 'FAILED' AND RETRY_COUNT < MAX_RETRIES;

-- Index theo aggregate — truy van toan bo event cua mot LTT
CREATE INDEX IDX_OUTBOX_AGGREGATE ON OUTBOX (AGGREGATE_TYPE, AGGREGATE_ID);

-- Index theo correlation id — tim kiem callback tu NHNN/NHTM
CREATE INDEX IDX_OUTBOX_CORRELATION ON OUTBOX (CORRELATION_ID);

-- Index theo kenh dich — loc event theo kenh MQ
CREATE INDEX IDX_OUTBOX_CHANNEL ON OUTBOX (TARGET_CHANNEL, STATUS);


-- ============================================================================
-- PL/SQL Package: OUTBOX_PKG — Helper cho xu ly outbox
-- ============================================================================
CREATE OR REPLACE PACKAGE OUTBOX_PKG IS

    -- === Tao event moi trong outbox (goi trong cung transaction voi LTT update) ===
    -- p_aggregate_type: 'LTT'
    -- p_aggregate_id: LTT.ID
    -- p_event_type: 'LTT_SUBMITTED', 'LTT_APPROVED', ...
    -- p_payload: JSON string
    -- p_target_channel: 'LNH', 'SP', 'LKB' hoac NULL
    -- p_target_queue: 'LNH.SEND.Q', ... hoac NULL
    -- p_correlation_id: correlation id tu LTT
    -- p_created_by: ma nguoi tao
    PROCEDURE INSERT_EVENT(
        p_aggregate_type  IN VARCHAR2,
        p_aggregate_id    IN NUMBER,
        p_event_type      IN VARCHAR2,
        p_payload         IN CLOB,
        p_target_channel  IN VARCHAR2 DEFAULT NULL,
        p_target_queue    IN VARCHAR2 DEFAULT NULL,
        p_correlation_id  IN VARCHAR2 DEFAULT NULL,
        p_idempotency_key IN VARCHAR2 DEFAULT NULL,
        p_created_by      IN VARCHAR2
    );

    -- === Danh dau event da publish thanh cong ===
    PROCEDURE MARK_PUBLISHED(
        p_id              IN NUMBER
    );

    -- === Danh dau event that bai va len lich retry ===
    -- Backoff: 5s (lan 1), 15s (lan 2), 45s (lan 3)
    PROCEDURE MARK_FAILED(
        p_id              IN NUMBER,
        p_error_message   IN VARCHAR2
    );

    -- === Lay PENDING events de xu ly (polling) ===
    -- p_limit: so luong event toi da can lay
    -- Tra ve ref cursor
    PROCEDURE GET_PENDING_EVENTS(
        p_limit   IN NUMBER,
        p_events  OUT SYS_REFCURSOR
    );

    -- === Don sach events da xu ly (chay dinh ky) ===
    -- Xoa events da PUBLISHED cu hon p_retention_days ngay
    PROCEDURE CLEANUP_PUBLISHED(
        p_retention_days IN NUMBER DEFAULT 30
    );

END OUTBOX_PKG;
/


CREATE OR REPLACE PACKAGE BODY OUTBOX_PKG IS

    ---------------------------------------------------------------------------
    -- INSERT_EVENT — Tao event moi
    ---------------------------------------------------------------------------
    PROCEDURE INSERT_EVENT(
        p_aggregate_type  IN VARCHAR2,
        p_aggregate_id    IN NUMBER,
        p_event_type      IN VARCHAR2,
        p_payload         IN CLOB,
        p_target_channel  IN VARCHAR2,
        p_target_queue    IN VARCHAR2,
        p_correlation_id  IN VARCHAR2,
        p_idempotency_key IN VARCHAR2,
        p_created_by      IN VARCHAR2
    ) IS
    BEGIN
        INSERT INTO OUTBOX (
            AGGREGATE_TYPE, AGGREGATE_ID, EVENT_TYPE, PAYLOAD,
            STATUS, TARGET_CHANNEL, TARGET_QUEUE,
            CORRELATION_ID, IDEMPOTENCY_KEY, CREATED_BY
        ) VALUES (
            p_aggregate_type, p_aggregate_id, p_event_type, p_payload,
            'PENDING', p_target_channel, p_target_queue,
            p_correlation_id,
            COALESCE(p_idempotency_key,
                     p_aggregate_type || '_' || p_aggregate_id || '_' || p_event_type || '_' ||
                     TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISSFF3')),
            p_created_by
        );
    END INSERT_EVENT;

    ---------------------------------------------------------------------------
    -- MARK_PUBLISHED — Danh dau da publish thanh cong
    ---------------------------------------------------------------------------
    PROCEDURE MARK_PUBLISHED(
        p_id              IN NUMBER
    ) IS
    BEGIN
        UPDATE OUTBOX
        SET STATUS       = 'PUBLISHED',
            PUBLISHED_AT = SYSTIMESTAMP
        WHERE ID = p_id;

        IF SQL%NOTFOUND THEN
            RAISE_APPLICATION_ERROR(-20001, 'Outbox event not found: ID=' || p_id);
        END IF;
    END MARK_PUBLISHED;

    ---------------------------------------------------------------------------
    -- MARK_FAILED — Danh dau that bai, len lich retry
    -- Backoff: lan 1 = +5s, lan 2 = +15s, lan 3 = +45s (BIZ-RETRY)
    ---------------------------------------------------------------------------
    PROCEDURE MARK_FAILED(
        p_id              IN NUMBER,
        p_error_message   IN VARCHAR2
    ) IS
        v_retry_count     NUMBER(3);
        v_max_retries     NUMBER(3);
        v_next_retry      TIMESTAMP;
        v_backoff_seconds NUMBER(10);
    BEGIN
        SELECT RETRY_COUNT, MAX_RETRIES
        INTO   v_retry_count, v_max_retries
        FROM   OUTBOX
        WHERE  ID = p_id
        FOR UPDATE;

        v_retry_count := v_retry_count + 1;

        -- Tinh backoff: 5, 15, 45 giay (BIZ-RETRY)
        IF v_retry_count = 1 THEN
            v_backoff_seconds := 5;
        ELSIF v_retry_count = 2 THEN
            v_backoff_seconds := 15;
        ELSE
            v_backoff_seconds := 45;
        END IF;

        v_next_retry := SYSTIMESTAMP + NUMTODSINTERVAL(v_backoff_seconds, 'SECOND');

        IF v_retry_count >= v_max_retries THEN
            -- Het lan retry → danh dau FAILED, khong retry nua
            UPDATE OUTBOX
            SET STATUS        = 'FAILED',
                RETRY_COUNT   = v_retry_count,
                ERROR_MESSAGE = SUBSTR(p_error_message, 1, 4000),
                NEXT_RETRY_AT = NULL
            WHERE ID = p_id;
        ELSE
            -- Con lan retry → danh dau PENDING, len lich retry
            UPDATE OUTBOX
            SET STATUS        = 'PENDING',
                RETRY_COUNT   = v_retry_count,
                ERROR_MESSAGE = SUBSTR(p_error_message, 1, 4000),
                NEXT_RETRY_AT = v_next_retry
            WHERE ID = p_id;
        END IF;
    END MARK_FAILED;

    ---------------------------------------------------------------------------
    -- GET_PENDING_EVENTS — Lay events cho polling
    ---------------------------------------------------------------------------
    PROCEDURE GET_PENDING_EVENTS(
        p_limit   IN NUMBER,
        p_events  OUT SYS_REFCURSOR
    ) IS
    BEGIN
        OPEN p_events FOR
            SELECT ID, AGGREGATE_TYPE, AGGREGATE_ID, EVENT_TYPE, PAYLOAD,
                   TARGET_CHANNEL, TARGET_QUEUE, CORRELATION_ID, RETRY_COUNT
            FROM   OUTBOX
            WHERE  STATUS = 'PENDING'
            AND    (NEXT_RETRY_AT IS NULL OR NEXT_RETRY_AT <= SYSTIMESTAMP)
            ORDER  BY CREATED_AT ASC
            FETCH  FIRST p_limit ROWS ONLY
            FOR UPDATE SKIP LOCKED;
    END GET_PENDING_EVENTS;

    ---------------------------------------------------------------------------
    -- CLEANUP_PUBLISHED — Xoa events da xu ly cu hon N ngay
    ---------------------------------------------------------------------------
    PROCEDURE CLEANUP_PUBLISHED(
        p_retention_days IN NUMBER DEFAULT 30
    ) IS
    BEGIN
        DELETE FROM OUTBOX
        WHERE  STATUS = 'PUBLISHED'
        AND    PUBLISHED_AT < SYSTIMESTAMP - NUMTODSINTERVAL(p_retention_days, 'DAY');

        COMMIT;
    END CLEANUP_PUBLISHED;

END OUTBOX_PKG;
/


-- ============================================================================
-- Oracle AQ (Advanced Queuing) — Tuy chon
-- Thay vi polling OUTBOX table, co the dung Oracle AQ de nhan thong bao
-- khi co event moi. Day la phuong an toi uu cho Oracle 19c.
-- ============================================================================

-- Tao AQ queue table (chi tao neu chua co)
BEGIN
    DBMS_AQADM.CREATE_QUEUE_TABLE(
        queue_table        => 'OUTBOX_QT',
        queue_payload_type => 'SYS.AQ$_JMS_TEXT_MESSAGE',
        multiple_consumers => FALSE,
        message_grouping   => DBMS_AQADM.NONE
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -24001 THEN  -- Da ton tai
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_AQADM.CREATE_QUEUE(
        queue_name  => 'OUTBOX_NOTIFY_Q',
        queue_table => 'OUTBOX_QT'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -24002 THEN  -- Da ton tai
            RAISE;
        END IF;
END;
/

BEGIN
    DBMS_AQADM.START_QUEUE('OUTBOX_NOTIFY_Q');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -25220 THEN  -- Queue dang chay
            RAISE;
        END IF;
END;
/

-- Trigger de gui thong bao AQ khi co event PENDING moi
CREATE OR REPLACE TRIGGER TRG_OUTBOX_NOTIFY
AFTER INSERT ON OUTBOX
FOR EACH ROW
WHEN (NEW.STATUS = 'PENDING')
DECLARE
    v_enqueue_options  DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_message_properties DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_message_handle   RAW(16);
    v_jms_message      SYS.AQ$_JMS_TEXT_MESSAGE;
BEGIN
    v_jms_message := SYS.AQ$_JMS_TEXT_MESSAGE.construct;
    v_jms_message.set_text(
        '{"outbox_id":' || :NEW.ID ||
        ',"event_type":"' || :NEW.EVENT_TYPE ||
        '","aggregate_type":"' || :NEW.AGGREGATE_TYPE ||
        '","aggregate_id":' || :NEW.AGGREGATE_ID || '}'
    );
    v_message_properties.priority := 1;

    DBMS_AQ.ENQUEUE(
        queue_name         => 'OUTBOX_NOTIFY_Q',
        enqueue_options    => v_enqueue_options,
        message_properties => v_message_properties,
        payload            => v_jms_message,
        msgid              => v_message_handle
    );
END;
/
