-- ============================================================================
-- V3__audit_hash_chain.sql — Kiem toan chuoi Hash (tamper-proof audit log)
-- Module: TT.OUT.MANUAL — Lenh thanh toan di NHNN thu cong
-- Oracle 19c DDL + PL/SQL
-- Generated: 2026-05-10 | SA + DBA — Stage 2
-- Reference: CLAUDE.md (Kiem toan chuoi Hash), CONTEXT.md (SHA-256),
--            business-rules.yaml (BIZ-AUDIT), validation-rules.yaml (VAL-036)
-- ============================================================================
--
-- Nguyen ly: Moi ban ghi kiem toan duoc tinh mot hash SHA-256 dua tren:
--   prev_hash + action + new_values + timestamp
-- Hash moi nay la unique va tao thanh mot chuoi (chain).
-- Neu bat ky ban ghi nao bi sua/xoa, chuoi se bi dut doan → phat hien gian lan.
--
-- Cong thuc hash:
--   current_hash = SHA-256(
--     prev_hash || action || JSON(new_values) || TO_CHAR(created_at, 'YYYY-MM-DDHH24MISSFF6')
--   )
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Bang LTT_AUDIT_HASH — Chuoi hash cho moi ban ghi kiem toan
-- ---------------------------------------------------------------------------
CREATE TABLE LTT_AUDIT_HASH (
    -- Khoa chinh
    ID                      NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- FK ve bang LTT
    LTT_ID                  NUMBER(20)      NOT NULL,

    -- Hanh dong (tuong ung voi LTT_AUDIT.ACTION)
    -- CREATE, EDIT, SUBMIT, APPROVE_CHECK, APPROVE, REJECT,
    -- CANCEL, SIGN, SEND, CONFIRM, REVERSE, DELETE, BLOCK, UNBLOCK
    ACTION                  VARCHAR2(30)    NOT NULL,

    -- Gia tri cu dang JSON — snapshot truoc khi thay doi
    OLD_VALUES              CLOB,

    -- Gia tri moi dang JSON — snapshot sau khi thay doi
    NEW_VALUES              CLOB,

    -- Hash cua ban ghi truoc do trong chuoi (lien ket)
    PREV_HASH               VARCHAR2(64)    NOT NULL,

    -- Hash hien tai — SHA-256(prev_hash + action + new_values + created_at)
    CURRENT_HASH            VARCHAR2(64)    NOT NULL,

    -- Nguoi thuc hien thao tac
    CREATED_BY              VARCHAR2(50)    NOT NULL,
    CREATED_BY_NAME         VARCHAR2(200),

    -- Thoi gian tao ban ghi
    CREATED_AT              TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Dia chi IP nguoi thao tac
    IP_ADDRESS              VARCHAR2(45),

    -- Trang thai truoc
    STATE_FROM              VARCHAR2(25),
    -- Trang thai sau
    STATE_TO                VARCHAR2(25),

    -- Phien ban truoc/sau
    VERSION_FROM            NUMBER(10),
    VERSION_TO              NUMBER(10),

    -- === Constraints ===
    CONSTRAINT PK_LTT_AUDIT_HASH PRIMARY KEY (ID),
    CONSTRAINT FK_LTT_AUDIT_HASH_LTT FOREIGN KEY (LTT_ID)
        REFERENCES LTT (ID) ON DELETE CASCADE,

    -- Current hash phai unique — dam bao khong co 2 ban ghi cung hash
    CONSTRAINT UQ_LTT_AUDIT_HASH_CURRENT UNIQUE (CURRENT_HASH),

    -- OLD_VALUES va NEW_VALUES phai la JSON hop le (neu co gia tri)
    CONSTRAINT CK_LTT_HASH_OLD_JSON CHECK (OLD_VALUES IS NULL OR OLD_VALUES IS JSON),
    CONSTRAINT CK_LTT_HASH_NEW_JSON CHECK (NEW_VALUES IS NULL OR NEW_VALUES IS JSON)
);

-- === Comments cho bang LTT_AUDIT_HASH ===
COMMENT ON TABLE  LTT_AUDIT_HASH IS 'Kiem toan chuoi Hash — tamper-proof audit log (SHA-256 chain)';
COMMENT ON COLUMN LTT_AUDIT_HASH.ID IS 'Khoa chinh tu tang';
COMMENT ON COLUMN LTT_AUDIT_HASH.LTT_ID IS 'FK ve bang LTT';
COMMENT ON COLUMN LTT_AUDIT_HASH.ACTION IS 'Hanh dong thuc hien — vi du: CREATE, EDIT, SUBMIT, APPROVE, ...';
COMMENT ON COLUMN LTT_AUDIT_HASH.OLD_VALUES IS 'Gia tri cu dang JSON — snapshot truoc khi thay doi';
COMMENT ON COLUMN LTT_AUDIT_HASH.NEW_VALUES IS 'Gia tri moi dang JSON — snapshot sau khi thay doi';
COMMENT ON COLUMN LTT_AUDIT_HASH.PREV_HASH IS 'Hash cua ban ghi truoc do trong chuoi — lien ket chuoi';
COMMENT ON COLUMN LTT_AUDIT_HASH.CURRENT_HASH IS 'Hash hien tai — SHA-256(prev_hash + action + new_values + created_at)';
COMMENT ON COLUMN LTT_AUDIT_HASH.CREATED_BY IS 'Ma nguoi thuc hien thao tac';
COMMENT ON COLUMN LTT_AUDIT_HASH.CREATED_BY_NAME IS 'Ten nguoi thuc hien thao tac';
COMMENT ON COLUMN LTT_AUDIT_HASH.CREATED_AT IS 'Thoi gian tao ban ghi';
COMMENT ON COLUMN LTT_AUDIT_HASH.IP_ADDRESS IS 'Dia chi IP cua nguoi thao tac';
COMMENT ON COLUMN LTT_AUDIT_HASH.STATE_FROM IS 'Trang thai LTT truoc thao tac';
COMMENT ON COLUMN LTT_AUDIT_HASH.STATE_TO IS 'Trang thai LTT sau thao tac';
COMMENT ON COLUMN LTT_AUDIT_HASH.VERSION_FROM IS 'Phien ban LTT truoc thao tac';
COMMENT ON COLUMN LTT_AUDIT_HASH.VERSION_TO IS 'Phien ban LTT sau thao tac';

-- === Index cho bang LTT_AUDIT_HASH ===
-- Tim kiem theo LTT_ID + thoi gian (xem lich su kiem toan)
CREATE INDEX IDX_LTT_HASH_LTT_TIME ON LTT_AUDIT_HASH (LTT_ID, CREATED_AT);

-- Tim kiem theo prev_hash — truy vet chuoi
CREATE INDEX IDX_LTT_HASH_PREV ON LTT_AUDIT_HASH (PREV_HASH);

-- Tim kiem theo nguoi thao tac
CREATE INDEX IDX_LTT_HASH_CREATED_BY ON LTT_AUDIT_HASH (CREATED_BY, CREATED_AT DESC);


-- ============================================================================
-- PL/SQL Package: AUDIT_HASH_PKG — Quan ly chuoi hash kiem toan
-- ============================================================================
CREATE OR REPLACE PACKAGE AUDIT_HASH_PKG IS

    -- === Them ban ghi kiem toan moi vao chuoi hash ===
    -- Tu dong lay prev_hash tu ban ghi cuoi cung cua LTT_ID
    -- va tinh current_hash
    --
    -- p_ltt_id: ID cua LTT
    -- p_action: Hanh dong (CREATE, EDIT, SUBMIT, ...)
    -- p_old_values: JSON snapshot truoc thay doi
    -- p_new_values: JSON snapshot sau thay doi
    -- p_created_by: Ma nguoi thao tac
    -- p_created_by_name: Ten nguoi thao tac
    -- p_ip_address: Dia chi IP
    -- p_state_from: Trang thai truoc
    -- p_state_to: Trang thai sau
    -- p_version_from: Phien ban truoc
    -- p_version_to: Phien ban sau
    --
    -- Tra ve: ID cua ban ghi audit hash vua tao
    FUNCTION APPEND_AUDIT(
        p_ltt_id          IN NUMBER,
        p_action          IN VARCHAR2,
        p_old_values      IN CLOB DEFAULT NULL,
        p_new_values      IN CLOB DEFAULT NULL,
        p_created_by      IN VARCHAR2,
        p_created_by_name IN VARCHAR2 DEFAULT NULL,
        p_ip_address      IN VARCHAR2 DEFAULT NULL,
        p_state_from      IN VARCHAR2 DEFAULT NULL,
        p_state_to        IN VARCHAR2 DEFAULT NULL,
        p_version_from    IN NUMBER DEFAULT NULL,
        p_version_to      IN NUMBER DEFAULT NULL
    ) RETURN NUMBER;

    -- === Xac minh toan bo chuoi hash cua mot LTT ===
    -- Kiem tra moi hash trong chuoi co hop le khong
    -- Neu co bat ky hash nao bi sua → tra ve FALSE
    --
    -- p_ltt_id: ID cua LTT can xac minh
    -- Tra ve: TRUE neu chuoi nguyen ven, FALSE neu co gian lan
    FUNCTION VERIFY_HASH_CHAIN(
        p_ltt_id IN NUMBER
    ) RETURN BOOLEAN;

    -- === Xac minh va tra ve ket qua chi tiet ===
    -- p_ltt_id: ID cua LTT can xac minh
    -- p_result: 'VALID' hoac 'INVALID'
    -- p_checked_count: So ban ghi da kiem tra
    -- p_error_detail: Mo ta loi (neu co)
    PROCEDURE VERIFY_HASH_CHAIN_DETAIL(
        p_ltt_id        IN  NUMBER,
        p_result        OUT VARCHAR2,
        p_checked_count OUT NUMBER,
        p_error_detail  OUT VARCHAR2
    );

    -- === Lay hash cuoi cung cua mot LTT (de prev_hash cho lan ghi tiep) ===
    FUNCTION GET_LAST_HASH(
        p_ltt_id IN NUMBER
    ) RETURN VARCHAR2;

END AUDIT_HASH_PKG;
/


CREATE OR REPLACE PACKAGE BODY AUDIT_HASH_PKG IS

    ---------------------------------------------------------------------------
    -- Tinh SHA-256 hash — Helper function
    -- Dau vao: chuoi can hash
    -- Dau ra: hex string SHA-256 (64 ky tu)
    ---------------------------------------------------------------------------
    FUNCTION COMPUTE_HASH(
        p_input IN VARCHAR2
    ) RETURN VARCHAR2 IS
        v_hash RAW(32);
    BEGIN
        -- Su dung DBMS_CRYPTO (Oracle 19c)
        -- DBMS_CRYPTO.HASH_SH256 = 4
        v_hash := DBMS_CRYPTO.HASH(
            src => UTL_I18N.STRING_TO_RAW(p_input, 'AL32UTF8'),
            typ => DBMS_CRYPTO.HASH_SH256
        );
        RETURN LOWER(RAWTOHEX(v_hash));
    END COMPUTE_HASH;

    ---------------------------------------------------------------------------
    -- GET_LAST_HASH — Lay hash cuoi cung cua mot LTT
    ---------------------------------------------------------------------------
    FUNCTION GET_LAST_HASH(
        p_ltt_id IN NUMBER
    ) RETURN VARCHAR2 IS
        v_hash VARCHAR2(64);
    BEGIN
        SELECT CURRENT_HASH
        INTO   v_hash
        FROM   LTT_AUDIT_HASH
        WHERE  LTT_ID = p_ltt_id
        ORDER  BY CREATED_AT DESC
        FETCH  FIRST 1 ROWS ONLY;

        RETURN v_hash;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            -- Khong co ban ghi nao — tra ve hash goc (genesis)
            -- Hash goc la SHA-256 cua 'TT.OUT.MANUAL.GENESIS'
            RETURN COMPUTE_HASH('TT.OUT.MANUAL.GENESIS.' || TO_CHAR(p_ltt_id));
    END GET_LAST_HASH;

    ---------------------------------------------------------------------------
    -- APPEND_AUDIT — Them ban ghi kiem toan moi
    ---------------------------------------------------------------------------
    FUNCTION APPEND_AUDIT(
        p_ltt_id          IN NUMBER,
        p_action          IN VARCHAR2,
        p_old_values      IN CLOB,
        p_new_values      IN CLOB,
        p_created_by      IN VARCHAR2,
        p_created_by_name IN VARCHAR2,
        p_ip_address      IN VARCHAR2,
        p_state_from      IN VARCHAR2,
        p_state_to        IN VARCHAR2,
        p_version_from    IN NUMBER,
        p_version_to      IN NUMBER
    ) RETURN NUMBER IS
        v_id          NUMBER(20);
        v_prev_hash   VARCHAR2(64);
        v_current_hash VARCHAR2(64);
        v_timestamp_str VARCHAR2(30);
        v_new_values_str VARCHAR2(32767);
    BEGIN
        -- Lay hash cua ban ghi truoc do
        v_prev_hash := GET_LAST_HASH(p_ltt_id);

        -- Cat ngan new_values de tinh hash (toi da 32767 ky tu)
        IF p_new_values IS NOT NULL THEN
            IF DBMS_LOB.GETLENGTH(p_new_values) > 32767 THEN
                v_new_values_str := DBMS_LOB.SUBSTR(p_new_values, 32767, 1);
            ELSE
                v_new_values_str := TO_CHAR(p_new_values);
            END IF;
        ELSE
            v_new_values_str := '{}';
        END IF;

        -- Tinh hash: SHA-256(prev_hash || action || new_values || timestamp)
        v_timestamp_str := TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DDHH24MISSFF6');
        v_current_hash := COMPUTE_HASH(
            v_prev_hash || '|' ||
            p_action || '|' ||
            v_new_values_str || '|' ||
            v_timestamp_str
        );

        -- Chen ban ghi moi
        INSERT INTO LTT_AUDIT_HASH (
            LTT_ID, ACTION, OLD_VALUES, NEW_VALUES,
            PREV_HASH, CURRENT_HASH,
            CREATED_BY, CREATED_BY_NAME, CREATED_AT, IP_ADDRESS,
            STATE_FROM, STATE_TO, VERSION_FROM, VERSION_TO
        ) VALUES (
            p_ltt_id, p_action, p_old_values, p_new_values,
            v_prev_hash, v_current_hash,
            p_created_by, p_created_by_name, SYSTIMESTAMP, p_ip_address,
            p_state_from, p_state_to, p_version_from, p_version_to
        )
        RETURNING ID INTO v_id;

        RETURN v_id;
    END APPEND_AUDIT;

    ---------------------------------------------------------------------------
    -- VERIFY_HASH_CHAIN — Xac minh toan bo chuoi hash cua mot LTT
    ---------------------------------------------------------------------------
    FUNCTION VERIFY_HASH_CHAIN(
        p_ltt_id IN NUMBER
    ) RETURN BOOLEAN IS
        v_cursor      SYS_REFCURSOR;
        v_id          NUMBER(20);
        v_action      VARCHAR2(30);
        v_new_values  CLOB;
        v_prev_hash   VARCHAR2(64);
        v_current_hash VARCHAR2(64);
        v_created_at  TIMESTAMP;
        v_expected    VARCHAR2(64);
        v_timestamp_str VARCHAR2(30);
        v_new_values_str VARCHAR2(32767);

        v_prev_chain_hash VARCHAR2(64);
        v_first_row    BOOLEAN := TRUE;
        v_count        NUMBER := 0;
    BEGIN
        -- Hash goc (genesis) cho ban ghi dau tien
        v_prev_chain_hash := COMPUTE_HASH('TT.OUT.MANUAL.GENESIS.' || TO_CHAR(p_ltt_id));

        OPEN v_cursor FOR
            SELECT ID, ACTION, NEW_VALUES, PREV_HASH, CURRENT_HASH, CREATED_AT
            FROM   LTT_AUDIT_HASH
            WHERE  LTT_ID = p_ltt_id
            ORDER  BY CREATED_AT ASC;

        LOOP
            FETCH v_cursor INTO v_id, v_action, v_new_values, v_prev_hash, v_current_hash, v_created_at;
            EXIT WHEN v_cursor%NOTFOUND;
            v_count := v_count + 1;

            -- Kiem tra prev_hash co khop voi hash cua ban ghi truoc do khong
            IF v_prev_hash != v_prev_chain_hash THEN
                CLOSE v_cursor;
                RETURN FALSE;
            END IF;

            -- Tinh lai hash va so sanh
            v_timestamp_str := TO_CHAR(v_created_at, 'YYYY-MM-DDHH24MISSFF6');

            IF v_new_values IS NOT NULL THEN
                IF DBMS_LOB.GETLENGTH(v_new_values) > 32767 THEN
                    v_new_values_str := DBMS_LOB.SUBSTR(v_new_values, 32767, 1);
                ELSE
                    v_new_values_str := TO_CHAR(v_new_values);
                END IF;
            ELSE
                v_new_values_str := '{}';
            END IF;

            v_expected := COMPUTE_HASH(
                v_prev_chain_hash || '|' ||
                v_action || '|' ||
                v_new_values_str || '|' ||
                v_timestamp_str
            );

            IF v_current_hash != v_expected THEN
                CLOSE v_cursor;
                RETURN FALSE;
            END IF;

            -- Cap nhat chain hash cho ban ghi tiep theo
            v_prev_chain_hash := v_current_hash;
        END LOOP;

        CLOSE v_cursor;

        -- Khong co ban ghi nao — hop le
        RETURN TRUE;

    EXCEPTION
        WHEN OTHERS THEN
            IF v_cursor%ISOPEN THEN
                CLOSE v_cursor;
            END IF;
            -- Loi khi xac minh → coi nhu khong hop le
            RETURN FALSE;
    END VERIFY_HASH_CHAIN;

    ---------------------------------------------------------------------------
    -- VERIFY_HASH_CHAIN_DETAIL — Xac minh va tra ve chi tiet
    ---------------------------------------------------------------------------
    PROCEDURE VERIFY_HASH_CHAIN_DETAIL(
        p_ltt_id        IN  NUMBER,
        p_result        OUT VARCHAR2,
        p_checked_count OUT NUMBER,
        p_error_detail  OUT VARCHAR2
    ) IS
        v_cursor      SYS_REFCURSOR;
        v_id          NUMBER(20);
        v_action      VARCHAR2(30);
        v_new_values  CLOB;
        v_prev_hash   VARCHAR2(64);
        v_current_hash VARCHAR2(64);
        v_created_at  TIMESTAMP;
        v_expected    VARCHAR2(64);
        v_timestamp_str VARCHAR2(30);
        v_new_values_str VARCHAR2(32767);

        v_prev_chain_hash VARCHAR2(64);
        v_count        NUMBER := 0;
    BEGIN
        v_prev_chain_hash := COMPUTE_HASH('TT.OUT.MANUAL.GENESIS.' || TO_CHAR(p_ltt_id));

        OPEN v_cursor FOR
            SELECT ID, ACTION, NEW_VALUES, PREV_HASH, CURRENT_HASH, CREATED_AT
            FROM   LTT_AUDIT_HASH
            WHERE  LTT_ID = p_ltt_id
            ORDER  BY CREATED_AT ASC;

        LOOP
            FETCH v_cursor INTO v_id, v_action, v_new_values, v_prev_hash, v_current_hash, v_created_at;
            EXIT WHEN v_cursor%NOTFOUND;
            v_count := v_count + 1;

            IF v_prev_hash != v_prev_chain_hash THEN
                CLOSE v_cursor;
                p_result := 'INVALID';
                p_checked_count := v_count;
                p_error_detail := 'Ban ghi ID=' || v_id || ': prev_hash khong khop voi hash truoc do. ' ||
                                  'Thuc te=' || SUBSTR(v_prev_hash, 1, 16) || '... Ky vong=' ||
                                  SUBSTR(v_prev_chain_hash, 1, 16) || '...';
                RETURN;
            END IF;

            v_timestamp_str := TO_CHAR(v_created_at, 'YYYY-MM-DDHH24MISSFF6');

            IF v_new_values IS NOT NULL THEN
                IF DBMS_LOB.GETLENGTH(v_new_values) > 32767 THEN
                    v_new_values_str := DBMS_LOB.SUBSTR(v_new_values, 32767, 1);
                ELSE
                    v_new_values_str := TO_CHAR(v_new_values);
                END IF;
            ELSE
                v_new_values_str := '{}';
            END IF;

            v_expected := COMPUTE_HASH(
                v_prev_chain_hash || '|' ||
                v_action || '|' ||
                v_new_values_str || '|' ||
                v_timestamp_str
            );

            IF v_current_hash != v_expected THEN
                CLOSE v_cursor;
                p_result := 'INVALID';
                p_checked_count := v_count;
                p_error_detail := 'Ban ghi ID=' || v_id || ' (action=' || v_action || '): ' ||
                                  'current_hash khong khop. ' ||
                                  'Thuc te=' || SUBSTR(v_current_hash, 1, 16) || '... Ky vong=' ||
                                  SUBSTR(v_expected, 1, 16) || '...';
                RETURN;
            END IF;

            v_prev_chain_hash := v_current_hash;
        END LOOP;

        CLOSE v_cursor;

        p_result := 'VALID';
        p_checked_count := v_count;
        p_error_detail := NULL;

    EXCEPTION
        WHEN OTHERS THEN
            IF v_cursor%ISOPEN THEN
                CLOSE v_cursor;
            END IF;
            p_result := 'INVALID';
            p_checked_count := v_count;
            p_error_detail := 'Loi he thong: ' || SQLERRM;
    END VERIFY_HASH_CHAIN_DETAIL;

END AUDIT_HASH_PKG;
/


-- ============================================================================
-- Grant quyen thuc thi cho DBMS_CRYPTO (can cho viec tinh SHA-256)
-- Can thuc hien boi DBA:
--   GRANT EXECUTE ON SYS.DBMS_CRYPTO TO <schema_owner>;
-- ============================================================================

-- ============================================================================
-- Trigger tu dong ghi audit hash khi co thay doi tren LTT
-- Day la backup — uu tien goi AUDIT_HASH_PKG.APPEND_AUDIT tu application layer
-- de co dieu khien tot hon tren noi dung JSON
-- ============================================================================

-- Lua chon: De application layer tu goi AUDIT_HASH_PKG.APPEND_AUDIT()
-- vi trigger khong co du context (old/new values JSON, IP address).
-- Trigger duoi day chi ghi hanh dong khi trang thai thay doi.

CREATE OR REPLACE TRIGGER TRG_LTT_AUDIT_HASH_STATE
AFTER UPDATE OF STATE ON LTT
FOR EACH ROW
DECLARE
    v_new_values CLOB;
    v_old_values CLOB;
BEGIN
    -- Chi ghi khi state thay doi
    IF :NEW.STATE != :OLD.STATE THEN
        -- Tao JSON don gian cho old/new state
        v_old_values := '{"state":"' || :OLD.STATE || '"}';
        v_new_values := '{"state":"' || :NEW.STATE || '"}';

        AUDIT_HASH_PKG.APPEND_AUDIT(
            p_ltt_id     => :NEW.ID,
            p_action     => 'STATE_CHANGE',
            p_old_values => v_old_values,
            p_new_values => v_new_values,
            p_created_by => COALESCE(:NEW.UPDATED_BY, :NEW.CREATED_BY),
            p_state_from => :OLD.STATE,
            p_state_to   => :NEW.STATE,
            p_version_from => :OLD.VERSION,
            p_version_to   => :NEW.VERSION
        );
    END IF;
END;
/
