-- ============================================================================
-- V4__lock_table.sql — Ho tro khoa lac quan (Optimistic Lock) va khoa phien
-- Module: TT.OUT.MANUAL — Lenh thanh toan di NHNN thu cong
-- Oracle 19c DDL + PL/SQL
-- Generated: 2026-05-10 | SA + DBA — Stage 2
-- Reference: CLAUDE.md (Khoa lac quan), business-rules.yaml (BIZ-OPTIMISTIC-LOCK),
--            validation-rules.yaml (VAL-033, VAL-036)
-- ============================================================================
--
-- Co che khoa:
--   1. Optimistic lock qua cot VERSION tren bang LTT (da co trong V1)
--      - Client gui If-Match header voi version hien tai
--      - Server kiem tra version client == version server
--      - Neu khac → reject (VAL-036)
--      - Neu gionp → cap nhat va tang version
--
--   2. Pessimistic lock qua bang LTT_LOCK (concurrent edit)
--      - Khi user mo form Edit, acquire lock
--      - Khi user dong form / thoat, release lock
--      - Lock co thoi gian het han (10 phut)
--      - Neu het han → lock tu giai phong
--      - Su dung SELECT ... FOR UPDATE SKIP LOCKED cho distributed lock
--
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Bang LTT_LOCK — Khoa phien (concurrent edit prevention)
-- Ho tro khoa phan tan qua nhieu node (OpenShift)
-- ---------------------------------------------------------------------------
CREATE TABLE LTT_LOCK (
    -- Khoa chinh
    ID                      NUMBER(20)      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- FK ve bang LTT
    LTT_ID                  NUMBER(20)      NOT NULL,

    -- Ma nguoi giu khoa
    LOCKED_BY               VARCHAR2(50)    NOT NULL,

    -- Thoi gian bat dau giu khoa
    LOCKED_AT               TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    -- Thoi gian het han khoa (mac dinh 10 phut)
    LOCK_EXPIRES_AT         TIMESTAMP       NOT NULL,

    -- Loai khoa
    -- EDIT: Khi mo form sua LTT
    -- DELETE: Khi mo popup xac nhan xoa
    -- SIGN: Khi dang ky so
    LOCK_TYPE               VARCHAR2(10)    DEFAULT 'EDIT' NOT NULL,

    -- Dia chi IP cua nguoi giu khoa
    IP_ADDRESS              VARCHAR2(45),

    -- Thong tin session / node (cho distributed lock)
    SESSION_ID              VARCHAR2(100),

    -- === Constraints ===
    CONSTRAINT PK_LTT_LOCK PRIMARY KEY (ID),
    CONSTRAINT FK_LTT_LOCK_LTT FOREIGN KEY (LTT_ID)
        REFERENCES LTT (ID) ON DELETE CASCADE,

    -- Moi LTT chi duoc co 1 lock active theo loai (EDIT/DELETE/SIGN)
    -- (Dam bao boi unique index co dieu kien — xem phan index phia duoi)

    CONSTRAINT CK_LTT_LOCK_TYPE CHECK (LOCK_TYPE IN ('EDIT', 'DELETE', 'SIGN')),

    -- Lock phai co thoi gian het han > thoi gian bat dau
    CONSTRAINT CK_LTT_LOCK_EXPIRY CHECK (LOCK_EXPIRES_AT > LOCKED_AT)
);

-- === Comments cho bang LTT_LOCK ===
COMMENT ON TABLE  LTT_LOCK IS 'Khoa phien (pessimistic lock) — chan chinh sua dong thoi (VAL-033)';
COMMENT ON COLUMN LTT_LOCK.ID IS 'Khoa chinh tu tang';
COMMENT ON COLUMN LTT_LOCK.LTT_ID IS 'FK ve bang LTT';
COMMENT ON COLUMN LTT_LOCK.LOCKED_BY IS 'Ma nguoi giu khoa';
COMMENT ON COLUMN LTT_LOCK.LOCKED_AT IS 'Thoi gian bat dau giu khoa';
COMMENT ON COLUMN LTT_LOCK.LOCK_EXPIRES_AT IS 'Thoi gian het han khoa — mac dinh 10 phut';
COMMENT ON COLUMN LTT_LOCK.LOCK_TYPE IS 'Loai khoa: EDIT (sua), DELETE (xoa), SIGN (ky so)';
COMMENT ON COLUMN LTT_LOCK.IP_ADDRESS IS 'Dia chi IP cua nguoi giu khoa';
COMMENT ON COLUMN LTT_LOCK.SESSION_ID IS 'Ma session / node — ho tro distributed lock';

-- === Index cho bang LTT_LOCK ===
-- Tim kiem lock theo LTT_ID (kiem tra lock nhanh)
CREATE INDEX IDX_LTT_LOCK_LTT_ID ON LTT_LOCK (LTT_ID);

-- Tim kiem lock theo nguoi giu (don dep lock cu)
CREATE INDEX IDX_LTT_LOCK_LOCKED_BY ON LTT_LOCK (LOCKED_BY);

-- Tim kiem lock da het han (tu dong don dep)
CREATE INDEX IDX_LTT_LOCK_EXPIRED ON LTT_LOCK (LOCK_EXPIRES_AT);


-- ============================================================================
-- PL/SQL Package: LTT_LOCK_PKG — Quan ly khoa phien
-- ============================================================================
CREATE OR REPLACE PACKAGE LTT_LOCK_PKG IS

    -- === Thoi gian het han khoa mac dinh (10 phut) ===
    LOCK_DURATION_MINUTES CONSTANT NUMBER := 10;

    -- === Acquire lock — Gianh quyen chinh sua LTT ===
    -- p_ltt_id: ID cua LTT can khoa
    -- p_user_id: Ma nguoi yeu cau khoa
    -- p_lock_type: 'EDIT', 'DELETE', hoac 'SIGN'
    -- p_ip_address: Dia chi IP
    -- p_session_id: Ma session / node
    --
    -- Tra ve:
    --   0 = Thanh cong
    --   1 = Da bi nguoi khac giu khoa (tra ve thong tin nguoi giu)
    --   2 = Ban ghi khong ton tai hoac da bi xoa
    PROCEDURE ACQUIRE_LOCK(
        p_ltt_id       IN  NUMBER,
        p_user_id      IN  VARCHAR2,
        p_lock_type    IN  VARCHAR2 DEFAULT 'EDIT',
        p_ip_address   IN  VARCHAR2 DEFAULT NULL,
        p_session_id   IN  VARCHAR2 DEFAULT NULL,
        p_result       OUT NUMBER,
        p_locked_by    OUT VARCHAR2,
        p_locked_until OUT TIMESTAMP
    );

    -- === Release lock — Giai phong khoa ===
    -- p_ltt_id: ID cua LTT can giai phong
    -- p_user_id: Ma nguoi yeu cau giai phong (chi nguoi giu moi duoc giai phong)
    -- p_lock_type: Loai khoa can giai phong
    --
    -- Tra ve:
    --   0 = Thanh cong
    --   1 = Khong tim thay lock
    --   2 = Lock bi giu boi nguoi khac
    PROCEDURE RELEASE_LOCK(
        p_ltt_id    IN  NUMBER,
        p_user_id   IN  VARCHAR2,
        p_lock_type IN  VARCHAR2 DEFAULT 'EDIT',
        p_result    OUT NUMBER
    );

    -- === Kiem tra LTT co dang bi khoa khong ===
    -- p_ltt_id: ID cua LTT can kiem tra
    -- Tra ve: TRUE neu dang bi khoa (va chua het han)
    FUNCTION IS_LOCKED(
        p_ltt_id IN NUMBER
    ) RETURN BOOLEAN;

    -- === Kiem tra LTT co bi khoa boi nguoi khac khong ===
    -- p_ltt_id: ID cua LTT
    -- p_user_id: Ma nguoi can kiem tra
    -- Tra ve: TRUE neu bi nguoi khac khoa
    FUNCTION IS_LOCKED_BY_OTHER(
        p_ltt_id IN NUMBER,
        p_user_id IN VARCHAR2
    ) RETURN BOOLEAN;

    -- === Don dep lock da het han ===
    -- Xoa toan bo lock da qua thoi gian het han
    -- Tra ve so lock da don dep
    PROCEDURE CLEANUP_EXPIRED_LOCKS(
        p_cleaned_count OUT NUMBER
    );

    -- === Giai phong toan bo lock cua mot user ===
    -- Dung khi user logout hoac session het han
    PROCEDURE RELEASE_ALL_USER_LOCKS(
        p_user_id IN VARCHAR2
    );

    -- === Verfy optimistic lock ===
    -- Kiem tra version client co khop voi version server khong
    -- p_ltt_id: ID cua LTT
    -- p_expected_version: Version tu client (If-Match header)
    -- Tra ve: TRUE neu version khop, FALSE neu khong khop (VAL-036)
    FUNCTION VERIFY_OPTIMISTIC_LOCK(
        p_ltt_id           IN NUMBER,
        p_expected_version IN NUMBER
    ) RETURN BOOLEAN;

    -- === Cap nhat LTT voi optimistic lock ===
    -- Chi cap nhat neu version khop, sau do tang version
    -- p_ltt_id: ID cua LTT
    -- p_expected_version: Version tu client
    -- p_updated_by: Ma nguoi cap nhat
    -- p_update_sql: Cap nhat SQL (SET clause) — goi tu application
    --
    -- Tra ve: So dong da cap nhat (0 = version khong khop, 1 = thanh cong)
    -- Uu tien: Goi tu application layer thay vi dung ham nay de co dieu khien tot hon

END LTT_LOCK_PKG;
/


CREATE OR REPLACE PACKAGE BODY LTT_LOCK_PKG IS

    ---------------------------------------------------------------------------
    -- ACQUIRE_LOCK — Gianh quyen chinh sua
    ---------------------------------------------------------------------------
    PROCEDURE ACQUIRE_LOCK(
        p_ltt_id       IN  NUMBER,
        p_user_id      IN  VARCHAR2,
        p_lock_type    IN  VARCHAR2 DEFAULT 'EDIT',
        p_ip_address   IN  VARCHAR2 DEFAULT NULL,
        p_session_id   IN  VARCHAR2 DEFAULT NULL,
        p_result       OUT NUMBER,
        p_locked_by    OUT VARCHAR2,
        p_locked_until OUT TIMESTAMP
    ) IS
        v_lock_id     NUMBER(20);
        v_locked_by   VARCHAR2(50);
        v_expires_at  TIMESTAMP;
    BEGIN
        -- Buoc 1: Don dep lock het han cua LTT nay
        DELETE FROM LTT_LOCK
        WHERE  LTT_ID = p_ltt_id
        AND    LOCK_TYPE = p_lock_type
        AND    LOCK_EXPIRES_AT < SYSTIMESTAMP;

        -- Buoc 2: Kiem tra lock active hien tai
        BEGIN
            SELECT ID, LOCKED_BY, LOCK_EXPIRES_AT
            INTO   v_lock_id, v_locked_by, v_expires_at
            FROM   LTT_LOCK
            WHERE  LTT_ID = p_ltt_id
            AND    LOCK_TYPE = p_lock_type
            FOR UPDATE NOWAIT;

            -- Da co lock active
            IF v_locked_by = p_user_id THEN
                -- Cung nguoi → gia han lock
                UPDATE LTT_LOCK
                SET    LOCK_EXPIRES_AT = SYSTIMESTAMP +
                         NUMTODSINTERVAL(LOCK_DURATION_MINUTES, 'MINUTE'),
                       IP_ADDRESS = p_ip_address,
                       SESSION_ID = p_session_id
                WHERE  ID = v_lock_id;

                p_result := 0;
                p_locked_by := p_user_id;
                p_locked_until := SYSTIMESTAMP +
                    NUMTODSINTERVAL(LOCK_DURATION_MINUTES, 'MINUTE');
                COMMIT;
                RETURN;
            ELSE
                -- Nguoi khac giu lock → tu choi
                p_result := 1;
                p_locked_by := v_locked_by;
                p_locked_until := v_expires_at;
                COMMIT;
                RETURN;
            END IF;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                NULL; -- Khong co lock → tiep tuc tao lock moi
        END;

        -- Buoc 3: Tao lock moi
        INSERT INTO LTT_LOCK (
            LTT_ID, LOCKED_BY, LOCKED_AT, LOCK_EXPIRES_AT,
            LOCK_TYPE, IP_ADDRESS, SESSION_ID
        ) VALUES (
            p_ltt_id, p_user_id, SYSTIMESTAMP,
            SYSTIMESTAMP + NUMTODSINTERVAL(LOCK_DURATION_MINUTES, 'MINUTE'),
            p_lock_type, p_ip_address, p_session_id
        );

        p_result := 0;
        p_locked_by := p_user_id;
        p_locked_until := SYSTIMESTAMP +
            NUMTODSINTERVAL(LOCK_DURATION_MINUTES, 'MINUTE');

        COMMIT;
    END ACQUIRE_LOCK;

    ---------------------------------------------------------------------------
    -- RELEASE_LOCK — Giai phong khoa
    ---------------------------------------------------------------------------
    PROCEDURE RELEASE_LOCK(
        p_ltt_id    IN  NUMBER,
        p_user_id   IN  VARCHAR2,
        p_lock_type IN  VARCHAR2 DEFAULT 'EDIT',
        p_result    OUT NUMBER
    ) IS
    BEGIN
        -- Chi xoa lock neu dung nguoi giu
        DELETE FROM LTT_LOCK
        WHERE  LTT_ID = p_ltt_id
        AND    LOCKED_BY = p_user_id
        AND    LOCK_TYPE = p_lock_type;

        IF SQL%ROWCOUNT > 0 THEN
            p_result := 0;  -- Thanh cong
        ELSE
            -- Kiem tra xem lock co ton tai khong (bi nguoi khac giu)
            FOR rec IN (
                SELECT LOCKED_BY FROM LTT_LOCK
                WHERE LTT_ID = p_ltt_id AND LOCK_TYPE = p_lock_type
            ) LOOP
                IF rec.LOCKED_BY != p_user_id THEN
                    p_result := 2;  -- Lock bi nguoi khac giu
                ELSE
                    p_result := 1;  -- Khong tim thay (da het han)
                END IF;
                COMMIT;
                RETURN;
            END LOOP;
            p_result := 1;  -- Khong tim thay lock
        END IF;

        COMMIT;
    END RELEASE_LOCK;

    ---------------------------------------------------------------------------
    -- IS_LOCKED — Kiem tra co dang bi khoa khong
    ---------------------------------------------------------------------------
    FUNCTION IS_LOCKED(
        p_ltt_id IN NUMBER
    ) RETURN BOOLEAN IS
        v_count NUMBER;
    BEGIN
        -- Don dep lock het han truoc
        DELETE FROM LTT_LOCK
        WHERE  LTT_ID = p_ltt_id
        AND    LOCK_EXPIRES_AT < SYSTIMESTAMP;

        SELECT COUNT(*)
        INTO   v_count
        FROM   LTT_LOCK
        WHERE  LTT_ID = p_ltt_id
        AND    LOCK_EXPIRES_AT >= SYSTIMESTAMP;

        RETURN v_count > 0;
    END IS_LOCKED;

    ---------------------------------------------------------------------------
    -- IS_LOCKED_BY_OTHER — Kiem tra co bi nguoi khac khoa khong
    ---------------------------------------------------------------------------
    FUNCTION IS_LOCKED_BY_OTHER(
        p_ltt_id  IN NUMBER,
        p_user_id IN VARCHAR2
    ) RETURN BOOLEAN IS
        v_count NUMBER;
    BEGIN
        DELETE FROM LTT_LOCK
        WHERE  LTT_ID = p_ltt_id
        AND    LOCK_EXPIRES_AT < SYSTIMESTAMP;

        SELECT COUNT(*)
        INTO   v_count
        FROM   LTT_LOCK
        WHERE  LTT_ID = p_ltt_id
        AND    LOCK_EXPIRES_AT >= SYSTIMESTAMP
        AND    LOCKED_BY != p_user_id;

        RETURN v_count > 0;
    END IS_LOCKED_BY_OTHER;

    ---------------------------------------------------------------------------
    -- CLEANUP_EXPIRED_LOCKS — Don dep lock het han
    ---------------------------------------------------------------------------
    PROCEDURE CLEANUP_EXPIRED_LOCKS(
        p_cleaned_count OUT NUMBER
    ) IS
    BEGIN
        DELETE FROM LTT_LOCK
        WHERE  LOCK_EXPIRES_AT < SYSTIMESTAMP;

        p_cleaned_count := SQL%ROWCOUNT;
        COMMIT;
    END CLEANUP_EXPIRED_LOCKS;

    ---------------------------------------------------------------------------
    -- RELEASE_ALL_USER_LOCKS — Giai phong toan bo lock cua user
    ---------------------------------------------------------------------------
    PROCEDURE RELEASE_ALL_USER_LOCKS(
        p_user_id IN VARCHAR2
    ) IS
    BEGIN
        DELETE FROM LTT_LOCK
        WHERE  LOCKED_BY = p_user_id;

        COMMIT;
    END RELEASE_ALL_USER_LOCKS;

    ---------------------------------------------------------------------------
    -- VERIFY_OPTIMISTIC_LOCK — Kiem tra version
    ---------------------------------------------------------------------------
    FUNCTION VERIFY_OPTIMISTIC_LOCK(
        p_ltt_id           IN NUMBER,
        p_expected_version IN NUMBER
    ) RETURN BOOLEAN IS
        v_actual_version NUMBER(10);
    BEGIN
        SELECT VERSION
        INTO   v_actual_version
        FROM   LTT
        WHERE  ID = p_ltt_id
        AND    IS_DELETED = 0;

        RETURN v_actual_version = p_expected_version;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN FALSE;
    END VERIFY_OPTIMISTIC_LOCK;

END LTT_LOCK_PKG;
/


-- ============================================================================
-- Oracle Job — Tu dong don dep lock het han moi 5 phut
-- ============================================================================
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_CLEANUP_EXPIRED_LOCKS',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN LTT_LOCK_PKG.CLEANUP_EXPIRED_LOCKS(:v_count); END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY; INTERVAL=5',
        enabled         => TRUE,
        comments        => 'Tu dong don dep lock het han cua LTT moi 5 phut'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -27477 THEN  -- Job da ton tai
            RAISE;
        END IF;
END;
/


-- ============================================================================
-- Oracle Job — Tu dong don dep OUTBOX da PUBLISHED (chay hang ngay luc 02:00)
-- ============================================================================
BEGIN
    DBMS_SCHEDULER.CREATE_JOB(
        job_name        => 'JOB_CLEANUP_PUBLISHED_OUTBOX',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN OUTBOX_PKG.CLEANUP_PUBLISHED(30); END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; BYHOUR=2; BYMINUTE=0; BYSECOND=0',
        enabled         => TRUE,
        comments        => 'Don dep OUTBOX events da PUBLISHED cu hon 30 ngay — chay hang ngay 02:00'
    );
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -27477 THEN  -- Job da ton tai
            RAISE;
        END IF;
END;
/


-- ============================================================================
-- Vi du su dung optimistic lock tu application layer (Spring Boot)
-- ============================================================================
-- Trong application, cap nhat LTT voi optimistic lock nhu sau:
--
-- @Transactional
-- public Ltt updateLtt(Long id, Long expectedVersion, LttUpdateRequest req, String userId) {
--     // 1. Kiem tra pessimistic lock (concurrent edit)
--     if (LTT_LOCK_PKG.is_locked_by_other(id, userId)) {
--         throw new ConcurrentEditException("LTT dang duoc nguoi khac chinh sua");
--     }
--
--     // 2. Kiem tra optimistic lock (version)
--     int updated = jdbcTemplate.update(
--         "UPDATE LTT SET amount = ?, updated_by = ? " +
--         "WHERE id = ? AND version = ? AND is_deleted = 0",
--         req.getAmount(), userId, id, expectedVersion
--     );
--
--     // 3. Neu updated = 0 → version khong khop (VAL-036)
--     if (updated == 0) {
--         throw new OptimisticLockException("Ban ghi da bi thay doi tu phien khac");
--     }
--
--     // 4. Trigger TRG_LTT_UPD_TIMESTAMP tu dong tang VERSION va cap nhat UPDATED_AT
--     // 5. Them audit log + audit hash
-- }
--
-- Hoac su dung JPA @Version:
--   @Version
--   private Long version;
--
-- ============================================================================
