-- Oracle 19c Schema for MVP Kho Bạc - Lệnh Thanh Toán (LTT)
-- Generated by SA Agent

-- 1. Table: LTT_TRANSACTION (Thông tin chung)
CREATE TABLE LTT_TRANSACTION (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CHANNEL             VARCHAR2(50) NOT NULL,          -- Kênh: Liên ngân hàng, TTSP
    TRANS_TYPE          VARCHAR2(100) NOT NULL,         -- Loại lệnh
    REF_NO              VARCHAR2(100) NOT NULL UNIQUE,  -- Số YCTT / Số bút toán
    SENDER_BANK         VARCHAR2(50) NOT NULL,          -- NH/KB chuyển
    RECEIVER_BANK       VARCHAR2(50) NOT NULL,          -- NH/KB nhận
    AMOUNT              NUMBER(18, 2) NOT NULL,         -- Tổng tiền
    CURRENCY_CODE       VARCHAR2(3) DEFAULT 'VND',      -- Loại tiền
    EXCHANGE_RATE       NUMBER(18, 4),                  -- Tỷ giá
    ORGIN_NUM           VARCHAR2(100),                  -- Số chứng từ gốc
    TRANS_DATE          DATE,                           -- Ngày chứng từ
    DESCRIPTION         VARCHAR2(1000) NOT NULL,        -- Nội dung thanh toán
    
    -- Trạng thái & Audit
    F_STATUS            VARCHAR2(50) DEFAULT 'Draft',   -- Trạng thái: Draft, Ready_For_Approval, Approved, etc.
    F_VER               NUMBER DEFAULT 1 NOT NULL,      -- Optimistic Locking
    CREATED_BY          VARCHAR2(50) NOT NULL,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(50),
    UPDATED_DATE        TIMESTAMP,
    CHECKED_BY          VARCHAR2(50),
    CHECKED_DATE        TIMESTAMP,
    APPROVED_BY         VARCHAR2(50),
    APPROVED_DATE       TIMESTAMP,
    
    -- Thông tin người chuyển (Flattened for performance)
    SENDER_NAME         VARCHAR2(255),
    SENDER_ADDRESS      VARCHAR2(500),
    SENDER_ACCOUNT      VARCHAR2(50),
    SENDER_IDENTIFY_ID  VARCHAR2(50),
    
    -- Thông tin người nhận (Flattened)
    RECEIVER_NAME       VARCHAR2(255),
    RECEIVER_ADDRESS    VARCHAR2(500),
    RECEIVER_ACCOUNT    VARCHAR2(50),
    RECEIVER_BANK_NAME  VARCHAR2(255)
);

-- 2. Table: LTT_DETAIL (Thông tin khoản mục / COA)
CREATE TABLE LTT_DETAIL (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRANS_ID            NUMBER NOT NULL,
    LINE_NO             NUMBER NOT NULL,
    GL_SEGMENT1         VARCHAR2(2),    -- Mã quỹ
    GL_SEGMENT2         VARCHAR2(4),    -- TK tự nhiên
    GL_SEGMENT3         VARCHAR2(7),    -- DVQHNS
    GL_SEGMENT4         VARCHAR2(10),   -- Cấp NS
    GL_SEGMENT5         VARCHAR2(3),    -- Chương
    GL_SEGMENT6         VARCHAR2(3),    -- Ngành KT
    GL_SEGMENT7         VARCHAR2(4),    -- NDKT
    GL_SEGMENT8         VARCHAR2(5),    -- ĐB
    GL_SEGMENT9         VARCHAR2(5),    -- CTMT
    GL_SEGMENT10        VARCHAR2(2),    -- MN
    GL_SEGMENT11        VARCHAR2(4),    -- Kho bạc
    GL_SEGMENT12        VARCHAR2(3),    -- DP
    AMOUNT              NUMBER(18, 2) NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    
    CONSTRAINT FK_LTT_DETAIL_TRANS FOREIGN KEY (TRANS_ID) REFERENCES LTT_TRANSACTION(ID) ON DELETE CASCADE
);

-- 3. Table: LTT_ATTACHMENT (Đính kèm)
CREATE TABLE LTT_ATTACHMENT (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRANS_ID            NUMBER NOT NULL,
    FILE_NAME           VARCHAR2(255) NOT NULL,
    DOC_TYPE            VARCHAR2(100),  -- Loại chứng từ
    FILE_SIZE           NUMBER,         -- Kích thước (bytes)
    FILE_HASH           VARCHAR2(64),   -- SHA-256
    FILE_PATH           VARCHAR2(500),  -- Đường dẫn lưu trữ
    UPLOADED_BY         VARCHAR2(50) NOT NULL,
    UPLOADED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT FK_LTT_ATTACH_TRANS FOREIGN KEY (TRANS_ID) REFERENCES LTT_TRANSACTION(ID) ON DELETE CASCADE
);

-- 4. Table: LTT_AUDIT_LOG (Lịch sử thao tác)
CREATE TABLE LTT_AUDIT_LOG (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRANS_ID            NUMBER NOT NULL,
    ACTION_TYPE         VARCHAR2(50) NOT NULL,  -- Event ID (NEW.SAVE, APPROVE.APPROVER, etc.)
    ACTOR               VARCHAR2(50) NOT NULL,
    ACTOR_ROLE          VARCHAR2(50),
    STATUS_FROM         VARCHAR2(50),
    STATUS_TO           VARCHAR2(50),
    OLD_VALUE           CLOB,                   -- Dữ liệu cũ (JSON)
    NEW_VALUE           CLOB,                   -- Dữ liệu mới (JSON)
    NOTE                VARCHAR2(500),          -- Lý do trả lại/từ chối/xoá
    CLIENT_IP           VARCHAR2(50),
    TIMESTAMP           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Indexes for performance
CREATE INDEX IDX_LTT_REF_NO ON LTT_TRANSACTION(REF_NO);
CREATE INDEX IDX_LTT_STATUS ON LTT_TRANSACTION(F_STATUS);
CREATE INDEX IDX_LTT_CREATED_DATE ON LTT_TRANSACTION(CREATED_DATE);
CREATE INDEX IDX_LTT_DETAIL_TRANS ON LTT_DETAIL(TRANS_ID);
CREATE INDEX IDX_LTT_AUDIT_TRANS ON LTT_AUDIT_LOG(TRANS_ID);
